aodn/nrmn-application

api/src/main/java/au/org/aodn/nrmn/restapi/controller/IngestionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/StagedRow.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/Survey.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/SurveyMethod.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/enums/StagedJobEventType.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/enums/StatusJobType.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/StagedRowFormatted.java
api/src/test/java/au/org/aodn/nrmn/restapi/model/db/SurveyMethodTestData.java
api/src/test/java/au/org/aodn/nrmn/restapi/model/db/SurveyTestData.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java

For https://github.com/aodn/backlog/issues/2357
Just lacking integration tests for the controller. The validation code isn't setting measures yet so my progress on that was stalled, but should be easy to finish off once the measures are in place (don't want to do any mocking since I really want to test that everything is working together [which of course it isn't right now due to the lack of measures])

Add an endpoint that ingests from a validated job

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/IngestionController.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/IngestionControllerIT.java
api/src/test/resources/testdata/FILL_DATA.sql

Finishes off https://github.com/aodn/backlog/issues/2357 by adding some basic integration tests for the ingestion controller, which couldn't be completed at the time of the original PR

Add ingestion integration test

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/CorrectionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/CorrectionService.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/CorrectionServiceTest.java

Work on implementing corrections for https://github.com/aodn/backlog/issues/2360

Corrections

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/IngestionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/StagedJobLogRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/StagedJobRepository.java

For use finding and selecting staged jobs
Also use consistent case for rest api tags

Add basic read operations on staged job and staged job log

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/StagedRowFormatted.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/RawValidation.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java

(the decimal place represents survey_num)

Store depth as integer in StagedRowFormatted

---

api/src/main/resources/application.properties

Redirect list requests received by the backend to the react app for handling
We switched from collection to list for these pages at some point and the front-end whitelist was not updated

Fixes aodn/backlog#2503

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/DiversController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/TemplateController.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SiteRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/TemplateService.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/TemplateServiceTest.java

https://github.com/aodn/backlog/issues/2454
Currently includes sites.csv and divers.csv. The species csvs will be added later.

Add template endpoint for getting a zip of template csvs

---

api/src/main/java/au/org/aodn/nrmn/restapi/model/db/Diver.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/Location.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/ObservableItem.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/Program.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/Site.java

Don't include null values in json responses for reference data - react-json-chema-form doesn't handle them correctly

Fixes aodn/backlog#2515 and aodn/backlog#2516

---

ui/src/components/data-entities/EntityList.js
ui/src/components/data-entities/GenericDetailsView.js
ui/src/index.css

A new branch due to to many merge conflicts 
Allows the generic view to link to configured pages per entity
For 
https://github.com/aodn/backlog/issues/2176

Generic details view

---

.github/workflows/maven.yml
ui/craco.config.js
ui/src/components/import/DataSheetView.js
ui/src/components/import/middleware/create-import.js
ui/src/components/import/middleware/validation-job.js
ui/src/components/import/reducers/create-import.js
ui/yarn.lock

The react warnings are still warnings in the dev environment while causing a build failure with `mvn clean package`

Build fails on react lint warnings

---

api/src/main/java/au/org/aodn/nrmn/restapi/model/db/Diver.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/Location.java
ui/src/components/data-entities/GenericForm.js

- Hide ID when displaying location and diver entities
- Make new location active by default
- Remove the id from the generic form header

Generic form changes

---

ui/.prettierrc

Tried to match the existing style.

Add Prettier config for UI project

---

ui/src/components/data-entities/CustomLoadingOverlay.js
ui/src/components/data-entities/EntityList.js

Fixes https://github.com/aodn/backlog/issues/2638

Fixes backlog/issues/2638

---

api/src/main/java/au/org/aodn/nrmn/restapi/assembler/ObservableItemListItemAssembler.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/ObservableItemController.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/observableitem/ObservableItemListItem.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/ObservableItemControllerIT.java
ui/src/components/data-entities/EntityList.js

Includes/requires  https://github.com/aodn/nrmn-application/pull/131

Display required subset of observable item attributes in list view

---

api/src/main/java/au/org/aodn/nrmn/restapi/assembler/ObservableItemListItemAssembler.java

Fixes issue displaying detail for observable item.

Observable item in list should link to the associated observable item NOT a site

---

ui/src/components/BaseForm.js
ui/src/components/data-entities/GenericForm.js
ui/src/components/data-entities/GenericForm.test.js

For https://github.com/aodn/backlog/issues/2635

Save and Cancel buttons for genericEntity forms

---

ui/src/components/data-entities/EntityList.js
ui/src/components/layout/SettingsMenu.js
ui/src/components/layout/theme-reducer.js

Adds DELETE CLONE buttons if configured 
The functions are not handled. 
Provided much better layout of tables when switching between entities, user switchable

EntityList delete and clone buttons. Table layout

---

ui/pom.xml
ui/src/components/layout/SideMenu.js

Display the application version set in `pom.xml` at the bottom of the side menu.

Add version label

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/DiverRepository.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/TemplateServiceTest.java
ui/src/components/data-entities/EntityList.js

Divers are now return sorted by intials, alphabetical first.
Delete & Clone buttons removed, New button restored.

Diver Management

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/LocationRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/springdatarest/BeforeCreateDiverValidator.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/springdatarest/BeforeSaveDiverValidator.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/springdatarest/BeforeSaveLocationValidator.java
api/src/test/java/au/org/aodn/nrmn/restapi/springdatarest/DiverApiIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/springdatarest/LocationApiIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/springdatarest/SiteApiIT.java
ui/package.json
ui/src/App.js
ui/src/axios/api.js
ui/src/components/data-entities/EntityList.js
ui/src/components/data-entities/EntityList.test.js
ui/src/components/data-entities/GenericDetailsView.js
ui/src/components/data-entities/GenericDetailsView.test.js
ui/src/components/data-entities/GenericForm.js
ui/src/components/data-entities/GenericForm.test.js
ui/src/components/data-entities/customWidgetFields/NestedApiField.js
ui/src/components/data-entities/customWidgetFields/NestedApiFieldDetails.js
ui/src/components/data-entities/form-reducer.js
ui/src/components/data-entities/middleware/entities.js
ui/src/components/layout/SideMenu.js
ui/yarn.lock

Location-specific fixes:
- Locations are returned by API by Location Name, grouping active at the top
- Remove Location delete button
Generic entity fixes:
- Fix message not displaying for generic entities when there is an error on creation
- Move all of the generic entity defintions out of the components and into App.js. This gives a single definition for all of the entity UI and allows routes to be generated programmatically from it instead of needing special error handling to handle non-existent entity types in each component.

Location API fixes and generic entity refactoring

---

api/src/main/java/au/org/aodn/nrmn/restapi/model/db/MarineProtectedArea.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/ObservableItem.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/ProtectionStatus.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/MarineProtectedAreaRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/ProtectionStatusRepository.java
api/src/main/resources/sql/application.sql
api/src/main/resources/sql/migration.sql

Also remove template_code from ObservableItem - its been removed from the db (merged with letter_code)

Add endpoints for ui_protection_status and ui_mpa

---

api/pom.xml
api/src/main/java/au/org/aodn/nrmn/restapi/repository/DiverRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/util/TimeUtils.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/entities/BaseRowExistingEntity.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/format/DateFormatValidation.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/format/TimeFormatValidation.java
api/src/test/java/au/org/aodn/nrmn/restapi/util/TimeUtilsTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/format/DateFormatTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/format/TimeFormatTest.java

Support additional date/time formats and case insensitive diver checks

---

ui/src/App.js
ui/src/components/data-entities/EntityEdit.js
ui/src/components/data-entities/EntityList.js
ui/src/components/data-entities/EntityList.test.js

Also: 
- Adds tool tips to the action buttons on the table
- Fixes a bug where returning to the Site table using a back arrow link show the table with only the Edit button visible
- Updates UI unit test to use the new entity template format

Implement Site Clone

---

ui/src/App.js
ui/src/App.test.js
ui/src/axios/api.js
ui/src/components/BaseForm.js
ui/src/components/data-entities/EntityEdit.js
ui/src/components/data-entities/EntityList.js
ui/src/components/data-entities/customWidgetFields/AutocompleteField.js
ui/src/components/data-entities/customWidgetFields/NestedApiField.js
ui/src/components/data-entities/middleware/entities.js
ui/src/components/layout/SideMenu.js

Implements the Site Delete function from the table. Also fixes a regression in the Location dropdown and improves error display.
http://nrmn-site-delete-updated.dev.aodn.org.au/

Site Delete

---

api/src/main/java/au/org/aodn/nrmn/restapi/dto/site/SiteDto.java
api/src/test/java/au/org/aodn/nrmn/restapi/springdatarest/SiteApiIT.java
ui/src/components/data-entities/EntityEdit.js
ui/src/components/data-entities/customWidgetFields/NestedApiField.js
ui/src/components/data-entities/customWidgetFields/NumberInput.js
ui/src/components/data-entities/customWidgetFields/TextInput.js
ui/src/components/data-entities/form-reducer.js

http://nrmn-site-validation.dev.aodn.org.au/

Display site validation errors on form

---

ui/src/components/data-entities/customWidgetFields/CheckboxInput.js
ui/src/components/data-entities/form-reducer.js
ui/src/components/data-entities/middleware/entities.js

- Location Edit and Diver Edit not redirecting correctly if there is no error on Save
- Location Add: Is Active is showing as False when this value defaults to True

Minor UI Fixes

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/ObservableItemController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/assembler/ObservableItemListItemAssembler.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/ObservableItemListItem.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/ObservableItemListItemRepository.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/ObservableItemControllerIT.java
ui/src/App.js
ui/src/components/data-entities/EntityList.js
ui/src/components/data-entities/ObservableItemTemplate.js

- Adds a ObservableItemListItemRepository to return list entries from `ep_observable_items` instead of `observable_item_ref`
- Wires up UI and implements an optional `sort` property to disable sorting on all columns except name and type.
http://nrmn-obs-item-list.dev.aodn.org.au/

Observable Items - List

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/ObservableItemGetDtoMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/observableitem/ObservableItemGetDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/ObservableItemRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/projections/ObservableItemRow.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/projections/ObservableItemSuperseded.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/projections/ObservableItemSupersededBy.java
ui/src/components/data-entities/EntityEdit.js
ui/src/components/data-entities/ObservableItemViewTemplate.js

- Rename 'Superseded By' fields to 'Superseded'
- Restore class column in table view
- Improve ObservableItemGetDto mapping

Observable Item fixes and improvements

---

api/src/main/java/au/org/aodn/nrmn/restapi/util/ValidatorHelpers.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/RawValidation.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/provider/ATRCValidators.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/provider/RLSValidators.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/format/IntegerFormatValidation.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/format/IntegerFormatTest.java

For https://github.com/aodn/backlog/issues/2730 ATRC and RLS Method valid checks
RLS:
ATRC:

aodn/backlog#2730 valid method checks RLS/ATRC

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/SurveyController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/SurveyDtoMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/survey/SurveyDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/Survey.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SurveyMethodRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SurveyRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/projections/SurveyRow.java
api/src/main/resources/application.properties
api/src/main/resources/sql/application.sql
api/src/test/java/au/org/aodn/nrmn/restapi/controller/SurveyControllerIT.java
ui/src/App.js
ui/src/components/data-entities/EntityEdit.js
ui/src/components/data-entities/EntityList.js
ui/src/components/data-entities/EntityView.js
ui/src/components/data-entities/SiteViewTemplate.js
ui/src/components/data-entities/SurveyEditTemplate.js
ui/src/components/data-entities/SurveyViewTemplate.js
ui/src/components/data-entities/customWidgetFields/TextInput.js
ui/src/components/layout/SideMenu.js

Survey List, View and Edit screens with matching API methods to handle the listing, viewing and editing of survey metadata.
Also rename `pq_diver_mod` to `pq_diver_id_mod` in the survey audit table.
Stack available at http://nrmn-survey-list-view-edit.dev.aodn.org.au connected to the `nrmn_dev` db.

Survey metadata management

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/StagedRowRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/model/StagedSurveyMethod.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/BaseGlobalValidator.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/provider/ATRCValidators.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/provider/RLSValidators.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/global/ATRCMethodCheck.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/global/BaseMethodCheck.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/global/RLSMethodBlockAssociation.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/global/RLSMethodCheck.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/global/ATRCMethodCheckIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/global/RLSMethodCheckIT.java

- Align ATRC method checking with spec
- Improve readability of error message
- Add RLS method check
Example API error response:
```
{
"job": {
"id": 4,
"reference": "small_maria.xlsx",
"isExtendedSize": false,
"status": "STAGED",
"source": "INGEST",
"program": {
"programId": 1,
"programName": "RLS",
"isActive": true
},
"created": "2021-03-28T23:08:33.196+0000",
"lastUpdated": "2021-03-28T23:08:34.216+0000",
"creator": {
"userId": 123456,
"version": 1,
"fullName": "Tanjona R",
"email": "test@gmail.com"
},
"logs": [
...
]
},
"errors": [],
"summaries": {},
"errorGlobal": [
...
{
"rowId": null,
"jobId": 4,
"message": "[ACEH1,2/04/2019,5.1] has incorrect set of methods: [2]",
"errorType": "GLOBAL",
"errorLevel": "WARNING",
"columnTarget": "RLS Method check"
},
{
"rowId": null,
"jobId": 4, …
```

ATRC and RLS method checks for aodn/backlog#2730

---

ui/src/components/data-entities/EntityList.js

Sometimes the columns fail to autosize when there has already been data loaded.

Fix column autosizing on entity list when data already loaded

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/SurveyController.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/survey/SurveyFilterDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SurveyRepository.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/SurveyControllerIT.java

The ugly casting appears to be necessary to work around null values being converted to type bytea. Please let me know if there is a better way of doing this.

Survey API: Implement filters needed for corrections page

---

ui/src/components/import/DataSheetView.js
ui/src/components/import/reducers/create-import.js

Should also disable Submit button while global errors are present.

Datasheet: Display global warnings and errors

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyContentsHandler.java
ui/src/components/import/JobUpload.js

Stack available at http://nrmn-ingest-remove-null.dev.aodn.org.au/

Job Upload: Store an empty string or measurement instead of null

---

ui/src/App.js
ui/src/axios/api.js
ui/src/axios/index.js
ui/src/index.js

Implements a global fallback message for unhandled errors. Also adds a 'last resort' error page when API unavailable.

Application-level error message

---

api/src/main/resources/sql/migration.sql

Align with recent migration database changes

Update migration sql

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
ui/src/components/import/DataSheetView.js
ui/src/components/import/reducers/create-import.js

when formattedRow errors or warnings are detected

Return combined formattedRow errors/warnings and global errors/warnings

---

ui/src/components/import/ValidationDrawer.js

Stack available at http://nrmn-error-highlighting.dev.aodn.org.au/

Differentiate row errors and warnings on data sheet

---

ui/src/components/data-entities/EntityList.js

Filters will now be retained when navigating away from a reference data list and back again. Also added a 'Reset Filter' button.
Demo: http://nrmn-bulk-edit.dev.aodn.org.au/reference/sites

Entity List: Persist filters between screens

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/IngestionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/StagedJobController.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/global/raw/RLSMethodBlockAssociation.java

Also some minor formatting fixes.

Perform ingestion in a single transaction

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/IngestionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
ui/src/components/import/ValidationJob.js

Refactor into a transactional method on the survey ingestion service
Wrap only the final commit in the transaction, excluding the survey id fetch
Display loading screen on submit.

Ingestion: refactor into a transactional method

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/ObservableItemController.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/observableitem/ObservableItemDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/observableitem/ObservableItemPutDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/ObservableItem.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/FormattedValidation.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/formatted/SpeciesBelongToMethodCheck.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/formatted/SpeciesBelongToMethodCheckTest.java

Also fix https://github.com/aodn/backlog/issues/3018 so I can keep associated methods when editing the observable item
Re-enable SpeciesBelongToMethodCheck

For aodn/backlog#2993 - Add allowed methods to observable item

---

api/src/main/java/au/org/aodn/nrmn/restapi/dto/site/SiteGetDto.java
ui/src/components/data-entities/customWidgetFields/TextInput.js

Also modifies the SiteGetDto to return these values as float not double.

Fix latitude and longitude not appearing in site details

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/SurveyMethodRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java

Spring JPA find by example can't handle site's with geometries.  Use a custom method to simplify the required processing.

Fix 'not a Object[] or List\!' issue

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/ObservableItemRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/WormsService.java
ui/src/axios/api.js
ui/src/components/data-entities/form-reducer.js
ui/src/components/search/SpeciesSearch.js

Also changes the NRMN search to do a substring match on species name instead of just checking the start of the string.
Stack at: http://nrmn-pagination.dev.aodn.org.au

Paginate species search results

---

ui/src/components/import/DataSheetView.js

http://nrmn-excel-export.dev.aodn.org.au/

Data Sheet: Show Export to Excel button

---

ui/src/components/import/DataSheetView.js
ui/src/components/import/ValidationJob.js

http://nrmn-export-settings.dev.aodn.org.au/home

Datasheet Export: Set default sheet, author and filename

---

api/src/main/java/au/org/aodn/nrmn/restapi/config/CacheConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/MeasureRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java

And update ingestion service unit tests to better test modified service.

Fix issue introduced in previous PR

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java

http://nrmn-size-classes.dev.aodn.org.au/ using nrmn_dev db

Additional size class mappings

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java

Stack deployed to http://nrmn-debris-m12.dev.aodn.org.au

Ingest: Save debris as M12

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java

http://nrmn-set-site-active.dev.aodn.org.au/

Survey Ingestion: Set site as active if not already active

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/ObservationRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/StagedRowFormatted.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/RawValidation.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/row/formatted/DebrisZeroObs.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/row/formatted/SpeciesBelongToMethodCheck.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/row/formatted/SpeciesNotSuperseeded.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/PreValidationProcessIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/RawValidationTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/formatted/DebrisZeroObsTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/formatted/FormattedTestProvider.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/formatted/SpeciesBelongToMethodCheckTest.java

Still need to add a test to verify survey not done survey methods added on ingestion.

aodn/backlog#3048 - create snd survey method records on ingestion

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/StagedRowRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/model/StagedSurveyTransect.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/global/raw/ATRCSurveyGroupComplete.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/global/ATRCSurveyGroupCompleteIT.java

For ATRC surveys validate that m1 has more than one record for block 1 and 2 and that m2 has more that one for block 1.

ATRC survey block validation

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/IngestionController.java
ui/src/components/import/DataSheetView.js
ui/src/components/import/middleware/validation-job.js
ui/src/components/import/reducers/create-import.js

Display any ingest errors as an alert on the datasheet page.

Improve error display on ingest submit

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/WormsService.java
ui/src/components/search/SpeciesSearch.js

ui may need to be updated as well - now fetching in page sizes of 500 (one page only for WORMS)

aodn/backlog#3128 - use names search instead of name search

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/ObservationRepository.java

correctly mapped to UiSpeciesAttributes properties when retrieving by id

Fixes aodn/backlog#3158 - ensure ui_species_attributes columns are

---

api/src/main/java/au/org/aodn/nrmn/restapi/dto/observableitem/ObservableItemDto.java
api/src/test/java/au/org/aodn/nrmn/restapi/springdatarest/ObservableItemApiIT.java

Fix missing class name on ObservableItemDto

---

api/src/main/java/au/org/aodn/nrmn/restapi/dto/observableitem/ObservableItemGetDto.java
api/src/test/java/au/org/aodn/nrmn/restapi/springdatarest/ObservableItemApiIT.java
ui/src/components/templates/ObservableItemViewTemplate.js

Add species epithet to ObservableItemGetDto and also update API tests.

Fix missing Species Epithet from Observable Item views

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/StagedRowFormatted.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/GlobalValidation.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/global/formatted/DuplicateRowCheck.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/global/formatted/DuplicateRowCheckTest.java

Backlog item: https://github.com/aodn/backlog/issues/3168

Check for duplicate rows

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java

based on site's mpa attribute.  MPA is not null, empty or whitespace on site -> 'yes' otherwise 'no'

aodn/backlog#3186 - set inside_marine_park to 'yes' or 'no' on ingestion

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/TemplateService.java
ui/src/components/datasheets/ExtractTemplateData.js

Also fix a bug with the download button not resetting after download is complete.

Template CSV Export: Set encoding to UTF-8

---

api/src/main/java/au/org/aodn/nrmn/restapi/RestApiApplication.java
api/src/main/java/au/org/aodn/nrmn/restapi/config/RLSClientConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SurveyRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/PQSurveyService.java
api/src/main/java/au/org/aodn/nrmn/restapi/tasks/ScheduledTasks.java
api/src/main/resources/application.properties
api/src/test/resources/application.properties

Backlog item: https://github.com/aodn/backlog/issues/3070
Task scheduled within Spring - Seems the cleanest out of the 3 methods, listed below for reference.
1. Run as Spring scheduled task
2. Run on request of surveys from webapp
2. Run from script on DB
- Payload is 18M
- Scheduled for midnight everyday

Scheduled task within spring to update pq fields

---

ui/src/components/import/DataSheetView.js
ui/src/components/import/panel/FindReplacePanel.js
ui/src/index.css

- Find & replace is not using column display order and is missing option for substring matching
- Undoing a cloned row is not removing the added row on undo
- Fix tool panel css so that it is wider by default

Datasheet fixes

---

api/src/main/java/au/org/aodn/nrmn/restapi/dto/species/SpeciesDto.java
ui/src/components/search/SpeciesSearch.js

Backlog item: https://github.com/aodn/backlog/issues/3214
Screenshot:

Add reason to superseded message

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/RawValidation.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/RawValidationTest.java

Backlog item: https://github.com/aodn/backlog/issues/3180

Persist PQ diver information

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/StagedRowFormatted.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/global/formatted/Method3QuadratsMissing.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/global/formatted/Method3QuadratsSum.java

Backlog item: https://github.com/aodn/backlog/issues/3203

Show affected rows for global validations

---

ui/src/components/import/DataSheetView.js

Deploying to http://nrmn-always-allow-save.dev.aodn.org.au

Always enable Save & Validate button on datasheet

---

api/src/main/java/au/org/aodn/nrmn/restapi/dto/observableitem/ObservableItemDto.java
ui/src/components/search/SpeciesSearch.js
ui/src/components/templates/ObservableItemTemplate.js

Backlog item: https://github.com/aodn/backlog/issues/3139
- Displays superseded by details in table
- Allows entering superseded by details for new records

View superseded by details in species search

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/SpeciesController.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/observableitem/ObservableItemPutDto.java
ui/src/components/data-entities/EntityEdit.js
ui/src/components/data-entities/customWidgetFields/AutoCompleteInput.js
ui/src/components/data-entities/form-reducer.js
ui/src/components/data-entities/middleware/entities.js

Backlog item: https://github.com/aodn/backlog/issues/3176

Edit higher taxonomic resolutions

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/RawValidation.java

Backlog item: https://github.com/aodn/backlog/issues/3233

Convert PQs missing error from blocking to warning

---

ui/src/components/import/DataSheetView.js

I've just replicated the delete functionality to multiple rows which appears to work even with filters. I haven't been able to find an issue after testing it so I am quite confident there shouldn't be any side effects.

Delete multiple rows

---

ui/src/components/import/DataSheetView.js

When an arrow is used within a cell then cell edit mode will be exited and navigated cell will be focused.

Excel-like arrow navigation when editing cells

---

ui/src/components/data-entities/customWidgetFields/SearchInput.js

Backlog item: https://github.com/aodn/backlog/issues/3130

Prevent non-result values being save as form value

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/SurveyRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/projections/SurveyRow.java
ui/src/App.js

Adds Site Code, Diver, Location name, Area, Country and has PQs.

Add columns to survey list query, DTO and UI schema

---

ui/src/components/data-entities/customWidgetFields/AutoCompleteInput.js

Backlog item: https://github.com/aodn/backlog/issues/3139

Update form with seleted species

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/SurveyDtoMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/survey/SurveyDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SurveyMethodRepository.java
ui/src/components/data-entities/customWidgetFields/TextInput.js
ui/src/components/templates/SurveyViewTemplate.js

Backlog item: https://github.com/aodn/backlog/issues/3038
Screenshot:
Same survey in edge right now: http://nrmn-edge.aodn.org.au/data/survey/812301392

Tweak survey view

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/ObservableItemController.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/ObservableItemRepository.java

Backlog item: https://github.com/aodn/backlog/issues/3130

Clear invalid superseded by in API

---

ui/src/components/job/JobView.js

Backlog item: https://github.com/aodn/backlog/issues/3113
Full/Large screen:
Half screen:

Replace timeline with table

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/SiteController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/SurveyController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/SurveyDtoMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/survey/SurveyDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/Survey.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SiteRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyEditService.java
api/src/main/java/au/org/aodn/nrmn/restapi/util/SpacialUtil.java
api/src/main/java/au/org/aodn/nrmn/restapi/util/TimeUtils.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/row/formatted/Within200MSiteCheck.java
ui/src/components/data-entities/EntityEdit.js
ui/src/components/data-entities/customWidgetFields/DropDownInput.js
ui/src/components/data-entities/form-reducer.js
ui/src/components/templates/SurveyEditTemplate.js

Backlog item: https://github.com/aodn/backlog/issues/3183

Allow editing of all non system fields in Survey

---

ui/src/components/search/SpeciesSearch.js

Backlog item: https://github.com/aodn/backlog/issues/3273

Populate new obs item form even if there is a warning

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/AuthController.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/AuthControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/IngestionControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/ObservableItemControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/SiteControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/SpeciesControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/StagedJobControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/SurveyControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/security/JwtTokenProviderIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/springdatarest/AphiaRefApiIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/springdatarest/DiverApiIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/springdatarest/LocationApiIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/springdatarest/ObservableItemApiIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/springdatarest/SiteApiIT.java
api/src/test/resources/testdata/TEST_USER.sql

Backlog item: https://github.com/aodn/backlog/issues/3173

3173 update test users

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/SurveyDtoMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SurveyRepository.java

Backlog item: https://github.com/aodn/backlog/issues/3294

Include diver names in survey list (Requires Optimisation)

---

api/pom.xml
api/src/main/java/au/org/aodn/nrmn/restapi/controller/StagedJobController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/StagedRowFormattedMapperConfig.java

Versions need to match up to what is displayed on the release page at https://github.com/reactor/reactor/releases.

Fix incompatible reactor-core + netty versions

---

api/src/main/java/au/org/aodn/nrmn/restapi/dto/site/SiteDto.java

Backlog item: https://github.com/aodn/backlog/issues/3298

Fix mandatory fields on Site

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/StagedRowFormattedMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
ui/src/components/import/JobUpload.js

- Error when Inverts column contained a string
- 'Verifying' loading bar not animating

Fix inverts validation and 'Verifying' loading bar not animating

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/ConfigController.java
api/src/main/resources/application.properties
ui/src/components/import/DataSheetView.js

Backlog item: https://github.com/aodn/backlog/issues/3295

AG Grid Config Endpoint

---

api/pom.xml

Backlog item: https://github.com/aodn/backlog/issues/3298

Move validation requirement back to pom

---

api/src/test/java/au/org/aodn/nrmn/restapi/controller/AuthControllerIT.java

Now that validations actually work this test fails - this fixes it.

Fix broken IT test

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/IngestionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/StagedRowFormattedMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/DiverRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/ObservableItemRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SiteRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/StagedRowRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/main/resources/application-dev.properties
api/src/main/resources/application.properties

Pre-cache data before mapping StagedRow to StagedRowFormatting.
Also fix typo in the survey group message and enable batch updates in Hibernate.

Faster Validation

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/StagedRowFormattedMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/StagedRowFormatted.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/row/format/ATRCDepthValidationTest.java

Implement survey group transect number valid validation

---

api/pom.xml
api/src/main/java/au/org/aodn/nrmn/restapi/controller/StagedJobController.java

Backlog item: https://github.com/aodn/backlog/issues/3300

Use correct s3 client

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationResultSet.java
ui/src/components/import/DataSheetView.js
ui/src/components/import/panel/ValidationPanel.js
ui/src/components/import/panel/ValidationSummary.js

Reset grid context on data load
Improve grouping for lat / long checks
Fix node ID not being created correctly for summary entries

Datasheet fixes & improvements

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java

Also allow blank and '0' as valid values.

Validation: allow direction to be case-insensitive

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/PQSurveyService.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyEditService.java

Also replace a deprecated function PQSurveyService

Survey edit: add visibility validation

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java

Return the missing methods and blocks in the error
Display as warning not blocking

Improve survey complete validation

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/StagedRowFormatted.java

For example see: http://nrmn-edge.aodn.org.au/validation/29

M3 validation: Fix crash when site is unknown

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/SurveyController.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/survey/SurveyDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyEditService.java

Backlog item: https://github.com/aodn/backlog/issues/3316

Remove use of modelmapper

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java

Backlog item: https://github.com/aodn/backlog/issues/3318

Filter out valid value of method and block both being 0

---

ui/src/App.js
ui/src/components/data-entities/EntityList.js

Allow sort on all columns except survey number, depth and time
Sort by Survey ID by default

Survey List: Improve sorting

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/DiverController.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/diver/DiverDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/Diver.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/DiverRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/springdatarest/DiverApiIT.java
ui/src/App.js

Backlog item: https://github.com/aodn/backlog/issues/3328

Validate Diver records on update and save

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/formatted/DebrisZeroObsTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/formatted/FormattedTestProvider.java

Prevent warnings when total is zero
Allow total of 1 if inverts is 1
Update tests

Update Debris Zero validation rule

---

api/src/main/java/au/org/aodn/nrmn/restapi/dto/survey/SurveyDto.java
ui/src/components/data-entities/EntityEdit.js

Backlog item: https://github.com/aodn/backlog/issues/3326

Make site name readonly on survey edit form

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyEditService.java

Related to https://github.com/aodn/nrmn-application/issues/503

Make survey edit coords message consistent with ingest errors

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/StagedRowFormattedMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/StagedRowFormatted.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/row/format/ATRCDepthValidationTest.java

Also add explicit error if method 0 doesn't have a block 0  and rework the survey naming methods to be more robust.

Survey Complete validation check not grouping correctly

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationResultSet.java
ui/src/components/import/panel/ValidationPanel.js

Group warnings at the end of the 'warnings' panel
Jump to each row on selection instead of filtering to set

Improve duplicate row warnings

---

ui/src/components/data-entities/EntityView.js

Backlog item: https://github.com/aodn/backlog/issues/3310

Show edit button on success screen

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/StagedJobController.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyContentsHandler.java

Also log the number of rows skipped that contain data

Stage only rows with IDs

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
ui/src/components/import/DataSheetView.js
ui/src/components/import/panel/ValidationPanel.js

Save and validate multiple comma-separated buddy names.
Also includes some minor UI improvements:
- Disable save button on load
- Hide global warnings section of the validation panel if there are none

Allow multiple divers in the Buddy column

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationResultSet.java
ui/src/components/import/panel/ValidationPanel.js

Fix global warning section never displaying
Prevent duplicate rows appearing multiple times in list
Order warning from top to bottom of sheet

Fix duplicate row warning

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/SiteRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcessIT.java

Backlog item: https://github.com/aodn/backlog/issues/3333

Make site code search case-insensitive

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/SurveyRepository.java
ui/src/App.js
ui/src/components/data-entities/EntityList.js

- Add back filter persistence
- Perform initial survey list sort in query instead of UI
- Change initial column sizing logic to only size the columns once after data load

Entity List improvements

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/SiteController.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SiteRepository.java
api/src/test/java/au/org/aodn/nrmn/restapi/springdatarest/SiteApiIT.java

Backlog item: https://github.com/aodn/backlog/issues/3120
Stack available at http://nrmn-new-site-distance-check.dev.aodn.org.au/home

Check site is not added or moved to within 200m from an existing site

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/formatted/FormattedTestProvider.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/formatted/SpeciesAbundanceCheckTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/formatted/TotalCheckSumTest.java

Validate SND and NSF Total/Inverts the same as DEZ

---

ui/src/components/import/panel/ValidationPanel.js

Clicking on the Duplicate Rows validation error did not jump to the correct location.

Fix duplicate validation highlighting

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/ObservableItemController.java

Backlog item: https://github.com/aodn/backlog/issues/3346

If superseded_by is "blank" set it to null

---

api/src/main/java/au/org/aodn/nrmn/restapi/model/db/StagedRow.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
ui/src/axios/api.js
ui/src/components/import/DataSheetView.js
ui/src/components/import/panel/ValidationPanel.js

Species: skip superseded validation if superseded value is am empty string
Duplicate rows: improve row hashing
Also fix a potential issue where the validation panel summary may not be refreshed on Save & Validate.

Validation improvements

---

ui/src/components/templates/SurveyEditTemplate.js
ui/src/components/templates/SurveyViewTemplate.js

Adds pq_url to the survey screen as well as reverse the order of lat/lon

Show PQ URL in survey details

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/StagedRowFormattedMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java

Backlog item: https://github.com/aodn/backlog/issues/3361

Ingest - Null check for direction + fix vis as double

---

api/src/main/java/au/org/aodn/nrmn/restapi/security/RequestRejectedExceptionFilter.java

Backlog item: https://github.com/aodn/backlog/issues/3353

Filter out request rejected exceptions

---

ui/src/components/import/DataSheetView.js

Backlog item: https://github.com/aodn/backlog/issues/3357

Full refresh after undo-ing anything

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java

Backlog item: https://github.com/aodn/backlog/issues/3377

Use correct case for P-Qs field name

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java

Display all of the missing / invalid method + block combos in a survey, not just the first one
Display block error if an ATRC M3 row has a block that isn't 0.

Improve Survey Complete validation check

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java

http://nrmn-m3-improvements.dev.aodn.org.au/

Change Survey Incomplete to become blocking if M3 block not 0

---

api/src/main/java/au/org/aodn/nrmn/restapi/dto/stage/ValidationResponse.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/StagedRow.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
ui/src/components/import/panel/ValidationPanel.js

Display a count of new sites, observable_items, and divers
Display a list of found sites
https://nrmn-summary.dev.aodn.org.au/

Ingest summary improvements

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java

Site & Diver count were not being done case-insensitive

Fix summary counts

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java

Fix site codes being validated case-sensitive after being edited.
Fix Survey Not Done being counted as a new observable item.

Minor summary fixes

---

app/pom.xml

Version we are using is from 2012 (!) and does not support Java 11.

Upgrade maven-war-plugin

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java

Add blocking validation if row no has no data and no value recorded for inverts and not SND, NSF or DEZ.
Stack available at http://nrmn-aodnstack-nspool.dev.aodn.org.au/

Inverts Validation

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyContentsHandler.java

Remove leading and trailing whitespace for all cell values.

Trim column values on staging

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/StagedRowFormatted.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java

Group by survey and method before generating observations, not just per-survey.
Deployed at http://nrmn-aodnstack-nspool.dev.aodn.org.au/home

Ingest: Fix regression when inserting observations

---

api/pom.xml
app/pom.xml
pom.xml
ui/pom.xml
ui/src/components/layout/SideMenu.js

Bump app version to 1.0 and hide build from the app. For example: http://nrmn-aodnstack-nspool.dev.aodn.org.au/home

Production Versioning

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/StagedJobController.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/stage/UploadResponse.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyContentsHandler.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
ui/src/components/import/JobUpload.js

- Only stage rows contains at least a diver, sitecode, date and depth.
- Remove any duplicates will leave one unique row at the end of the sheet (for non species) otherwise remove all duplicated rows for rows at the end of the sheet that have Total = 0.
- Improve user feedback on upload.

Staging Improvements

---

api/pom.xml
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyEditService.java
app/pom.xml
pom.xml
ui/pom.xml

Stack at: http://nrmn-aodnstack-nspool.dev.aodn.org.au/

Fix Survey Edit DTO Mapping

---

scripts/drop_ep_survey_list_view.sql
scripts/update_ep_survey_list_view.sql

This is only the SQL script to replace the command for the field "has_pqs_catalogued_in_db".

Fix pq catalogue in view

---

scripts/db-update/03-add_missing_prod_views.sql

```
ep_m0_off_transect_sighting_public 
ep_m1_public
ep_m2_cryptic_fish_public
ep_m2_inverts_public
ep_m3_isq_public
ep_m4_macrocystis_count_public
ep_m5_limpet_quadrats_public
ep_m11_off_transect_measurement_public 
ep_m13_pq_scores_public 
ep_survey_list_public
```

Script to add views missing in prod and systest

---

api/src/main/java/au/org/aodn/nrmn/restapi/dto/stage/ValidationResponse.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/SurveyExistsIT.java
ui/src/components/import/panel/ValidationPanel.js

- Add existing survey count to response
- Display the existing survey count underneath the number of distinct surveys
- Update tests.

Display count of existing surveys found

---

ui/src/components/import/DataSheetView.js

Do not reset the filter or sheet position on save.
Also fix the columns resizing to minimum width after a full reload.

Remember datasheet filter and position on save

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/SiteController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/TemplateController.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SiteRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/TemplateService.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/TemplateServiceTest.java
ui/src/components/datasheets/ExtractTemplateData.js

'Country' is now an option under Template Data > Area Type.

Add Country to template generator

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/LocationController.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/LocationRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/projections/LocationExtendedMapping.java
ui/src/App.js
ui/src/components/data-entities/location/LocationList.js
ui/src/components/import/DataSheetView.js
ui/src/components/job/JobList.js
ui/src/components/overlays/LoadingOverlay.js
ui/src/index.css

Display countries, areas and eco-regions for each location.
General UI improvements to the table display.

Add columns to Location List

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/SurveyDtoMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/survey/SurveyDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SurveyRepository.java
ui/src/App.js
ui/src/components/data-entities/EntityView.js
ui/src/components/data-entities/survey/SurveyList.js
ui/src/components/templates/SurveyViewTemplate.js
ui/src/index.css

In the survey list and survey view the full depth depth will be displayed and it is possible to filter by decimal depth.
Stack available at: http://nrmn-aodnstack-nspool.dev.aodn.org.au

Display decimal depth in survey views

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/LocationRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/projections/LocationExtendedMapping.java
ui/src/components/data-entities/location/LocationList.js
ui/src/components/data-entities/survey/SurveyList.js

Fix locations not associated with a site not appearing in the list.
Also reset the redux form on list load.

Fix location list query

---

api/pom.xml
app/pom.xml
bumpversion.sh
pom.xml
ui/pom.xml

For https://github.com/aodn/backlog/issues/2616

Make versions get bumped via git tags

---

Jenkinsfile

For https://github.com/aodn/backlog/issues/2616

Remove version bumps from dev builds

---

api/src/main/java/au/org/aodn/nrmn/restapi/dto/stage/ValidationError.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/survey/SurveyDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationResultSet.java
ui/src/components/data-entities/location/LocationList.js
ui/src/components/data-entities/survey/SurveyList.js
ui/src/components/import/panel/ValidationPanel.js

- Include Buddy & PQ divers in Diver Summary values
- Use text as the default filter on Location and Survey lists
- Rename "Decimal Depth" to just "Depth" on Survey View

Summary & Display Fixes

---

Dockerfile

Part of https://github.com/aodn/backlog/issues/2616

Install bump2version in docker

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyEditService.java

Add ATRC date validation to be after 1-1-1991
Allow blank value for direction

Edit survey improvements

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java

Rework the summary count to work the same way the validation does and compare the initials against the diver list.

Fix summary count

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java

Fixes the count when entering a diver with initials in one column and full name in another.

Summary: Map name to initial before diver count

---

.bumpversion.cfg
Dockerfile
bumpversion.sh

For https://github.com/aodn/backlog/issues/2616

Bump2version

---

ui/src/App.js
ui/src/components/data-entities/location/LocationList.js
ui/src/components/data-entities/survey/SurveyList.js

Filter selection should be save when leaving and returning to the location list.

Persist location list filter between navigations

---

api/src/main/java/au/org/aodn/nrmn/restapi/dto/stage/ValidationError.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/StagedRow.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/enums/ValidationCategory.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/enums/ValidationLevel.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationResultSet.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/ATRCSurveyGroupCompleteIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/MeasureJsonValidationTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/RLSMethodBlockAssociationIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/RLSMethodCheckIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcessTest.java
ui/src/App.js
ui/src/components/import/DataSheetView.js
ui/src/components/import/panel/ValidationPanel.js
ui/src/components/import/panel/ValidationSummary.js
ui/src/components/layout/Homepage.js
ui/src/components/ui/LinearProgressWithLabel.js

Group duplicate row validations by species
No longer filter when clicking on a validation
Remove the Total from the row hash when determining duplicates
Add Info level for measurement related validations
Move Reset button from tool panel to header row.
Show duplicate rows as bold when focused.

Improve Duplicate Row Validation

---

ui/src/components/import/DataSheetView.js

Add Undo button
Keep undo history between resloads
Bind Ctrl-Z to window not just grid

Datasheet undo improvements

---

ui/src/components/import/DataSheetView.js

Specifically fixes the undo count not incrementing after Find & Replace.

Set undo size on data edit events

---

ui/src/components/data-entities/survey/SurveyList.js

* Not persisting filters
* Opening the wrong URL on ctrl-click Edit

Survey List Fixes

---

ui/yarn.lock

See https://github.com/browserslist/browserslist#browsers-data-updating

Update CanIUse library

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyEditService.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/WormsService.java
ui/src/App.js
ui/src/axios/api.js
ui/src/components/data-entities/ObservableItemAdd.js
ui/src/components/search/SpeciesSearch.js

/AphiaRecordsByNames is not returning more than 50 results. Changed to /AphiaRecordsByName/ which supports paging.
Also replace redux usage with a react reducer and consolidate axios calls needed for page autocomplete.

Update WoRMS endpoint used for species search

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/ObservableItemController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/StagedRowFormattedMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/survey/SurveyFilterDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/StagedRow.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SurveyRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SpreadSheetService.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyEditService.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/WormsService.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationResultSet.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SpreadSheetServiceIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/DirectionDataCheckTest.java
ui/src/components/import/DataSheetView.js

PQ Update: Update survey if pq_catalogued is null
Grid: Trim cell values on edit
API: Remove explicit calls to trim() and replace null checks on strings with StringUtils.

Improve null and empty string handling

---

.github/workflows/maven.yml
api/src/main/resources/application-test.properties

To prevent PQ update from running during integration tests.

github workflow: add test profile

---

.github/workflows/maven.yml
api/src/test/resources/application.properties

Tests are failing when running locally due to the missing test profile which is causing the PQ update to run (and fail) on each test.

Set test profile in JUnit config

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java
ui/src/components/import/panel/ValidationPanel.js
ui/src/components/layout/AuthState.js

Implements an Admin role to ignore blocking validations and allow the additional ATRC data to be ingested.

Allow users with admin role to ingest sheets with blocking validations

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java

Store survey visibility as average of all non-empty rows instead of taking value from first row.

Survey visibility: Store as average

---

ui/src/components/import/DataSheetView.js
ui/src/components/import/panel/ValidationSummary.js

Show either invert or fish measurement in size class validation messages, not both.

Improve size class validation feedback

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/ObservableItemController.java
ui/src/components/data-entities/EntityView.js
ui/src/components/data-entities/ObservableItemAdd.js
ui/src/components/data-entities/ObservableItemEdit.js

show delete button in observable item edit
add delete endpoint to api
extend entity view to show item deleted if passed with id -1
add ui validation to prevent invalid aphia ids

Delete Observable Item feature

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java
ui/src/components/import/panel/ValidationSummary.js

- Round survey visibility to 1 decimal place.
- Hide duplicate measurement warnings in the validation summary.

survey ingest: round visibility to 1 decimal place

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/StagedRowFormattedMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyEditService.java

- Correctly null out diver if empty diver is selected in survey edit
- Fix string comparison when normalising diver name on ingest

Fix Diver Name mapping

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java

These predicates need to be broken out into separate methods. But for now I have left them inline.

Use normalised names in diver counts

---

Dockerfile

http://nrmn-cmrose3.dev.aodn.org.au/home
https://imos-artifacts.s3.ap-southeast-2.amazonaws.com/builds/nrmn-application_build/3708-set-ubuntu20/1/artifacts/nrmn-app-0.0.0.war

ubuntu20, libnetcdf15, libgsl23 in docker file

---

Dockerfile
Jenkinsfile

Try and fix intermittent bumpversion issues by adding back the `git reset --hard` Jenkins step.

Jenkinsfile: add back git reset

---

bumpversion.sh

Reverts aodn/nrmn-application#864

Revert "bumpversion: add debugging"

---

bumpversion.sh

Reverts aodn/nrmn-application#866

Revert "bumpversion: add verbose option"

---

api/pom.xml
api/src/main/java/au/org/aodn/nrmn/restapi/controller/SiteController.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/observableitem/ObservableItemDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/observableitem/ObservableItemGetDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/observableitem/ObservableItemPutDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/site/SiteDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/site/SiteGetDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/survey/SurveyDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/Diver.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/Location.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/Site.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/projections/ObservableItemRow.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/projections/SurveyRow.java
api/src/main/resources/application.properties
api/src/test/java/au/org/aodn/nrmn/restapi/controller/SiteControllerIT.java
web/src/components/data-entities/site/SiteList.js
web/src/components/data-entities/survey/SurveyEdit.js

Rename the `/siteListItems` endpoint to `/sites`
Remove some `@Schema` annotation that are no longer needed
Remove an unnecessary AWS dependency

Minor API cleanup

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/SiteController.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SiteRepository.java
api/src/test/java/au/org/aodn/nrmn/restapi/test/annotations/WithNoData.java
api/src/test/java/au/org/aodn/nrmn/restapi/test/annotations/WithTestData.java
api/src/test/resources/testdata/FILL_DATA.sql
api/src/test/resources/testdata/FILL_ROLES.sql
api/src/test/resources/testdata/TEST_USER.sql
web/src/api/api.js
web/src/components/data-entities/location/LocationView.js
web/src/components/data-entities/observable-item/ObservableItemAdd.js
web/src/components/data-entities/observable-item/ObservableItemEdit.js
web/src/components/data-entities/observable-item/ObservableItemView.js
web/src/components/data-entities/site/SiteEdit.js
web/src/components/data-entities/site/SiteView.js

Fixes:
- Add new Observable Item: redirect to blank page on Save
- Add new Observable Item: says 'Back to Sites" instead of "Back to Observable Items"
- New Site view : "Save site" redirects to home page
- Delete observable Item: request fails with status 404
- Ingest : warning "coordinate differ from site" reports different of the order of cm. 
- Site View: missing location name
- Location View: Edit button doesn't have a border
Coordinate warning will only appear if different > 10m and < 200m radius.

Fix regressions

---

.vscode/launch.json
web/src/App.test.tsx
web/src/components/auth/LoginForm.test.tsx
web/src/components/ui/AlertDialog.test.tsx

Specifically so that mocked web requests and responses can be typed to match Spring Boot as closely as possible.

Use TypeScript for UI Tests

---

api/src/main/java/au/org/aodn/nrmn/restapi/config/SecurityConfig.java
api/src/main/resources/application-dev.properties
api/src/main/resources/application.properties
api/src/test/resources/application.properties
web/yarn.lock

- Enable CSRF by default
- Add configuration property to disable in development

Enable CSRF by default

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/IngestionController.java

Exceptions during ingest should be logged.

Log ingestion errors instead of returning to user

---

api/src/main/java/au/org/aodn/nrmn/restapi/config/SecurityConfig.java
api/src/main/resources/application.properties

Disable CSRF for now as token is missing from UI

Disable CSRF

---

web/package.json
web/yarn.lock

27.2 appears to have a breaking change preventing grids from rendering.

Ag Grid: Revert to version 27.1

---

web/src/api/api.js
web/src/api/index.js
web/src/components/import/JobUpload.js

This PR put the API version number in the Axios config so that if we ever want to bump it there's only one place we'll need to change.

Set API version in Axios config

---

api/src/main/java/au/org/aodn/nrmn/restapi/dto/correction/CorrectionRowDto.java
web/src/components/data-entities/survey/SurveyCorrect.js

- SND is missing from the DTO
- Field name not being set correctly for boolean fields resulting in them always showing false.

Survey Correction View: Fix UseInvertSizing and Survey Not Done columns always showing false

---

web/src/components/data-entities/site/SiteList.js

Add missing icons in site list, there is a problem with the delete icon and will be address with different ticket 
https://github.com/aodn/backlog/issues/4036

Add back missing icons

---

api/src/main/resources/application-dev.properties
web/src/components/data-entities/observable-item/ObservableItemView.js

Trying to render other attributes as a string and not a key/value object.

Observable Item View: Fix attribute display

---

api/src/main/java/au/org/aodn/nrmn/restapi/model/db/StagedJob.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcessTest.java

Skip isInvertSizing column validation if not an extended sheet

---

web/src/components/data-entities/observable-item/__test__/ObservableItemView.test.tsx

Fixed the ObsItemAttribute not rendering correctly in PR https://github.com/aodn/nrmn-application/pull/1017.
This PR adds a test to prevent it breaking again.

Add Jest test for ObservableItemView

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/LocationController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/StagedJobController.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/AuthControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/IngestionControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/ObservableItemControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/SiteControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/SpeciesControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/SurveyControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/springdatarest/DiverApiIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/springdatarest/LocationApiIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/springdatarest/ObservableItemApiIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/springdatarest/SiteApiIT.java
web/package.json
web/src/App.js
web/src/components/data-entities/site/__test__/SiteList.test.tsx
web/src/components/import/__test__/DataSheetView.test.tsx
web/yarn.lock

api tests: replace deprecated functions
web tests: reduce verbosity and add typescript annotations

Improve Tests

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/Method3QuadratsSumTest.java

Quadrats 1-5 should sum to at least 50 but each individual quadrat should be no greater than 50.

Validation: M3 quadrats should be more greater than 50

---

web/src/components/import/DataSheetView.js
web/src/components/import/__test__/DataSheetView.test.tsx

Based on "Sorting Formatted Dates" https://blog.ag-grid.com/valueformatters-part-2/

Implement Ag Grid custom date comparator for sorting

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/ATRCSurveyGroupCompleteIT.java

Change Survey Group validation level from Blocking to Warning.
Improve integration test.
Needs this PR merged first to fix CodeQL error: https://github.com/aodn/nrmn-application/pull/1078

Change ATRC Survey Group validation from Blocking to Warning

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/ATRCSurveyGroupCompleteIT.java

Add site, date and depth to message and change 'missing' to 'missing transect'

Improve survey group validation message

---

api/src/main/java/au/org/aodn/nrmn/restapi/config/SecurityConfig.java

Looks like the current master failed too when running on my PC, the branch build 1212-WORM-search build is fine so I believe one it is merged to master, this build should work too

remove deprecated class

---

web/src/App.js

Feedback indicated that the font size is too small.

Increase font size of Species Search results

---

api/src/main/java/au/org/aodn/nrmn/restapi/config/RateLimitInterceptor.java

Exclude local subnet IPs from rate limiting

---

web/src/components/data-entities/survey/SurveyEdit.js

Adds a link to the corrections page from the survey edit page.

Add a Correct Survey button to the Survey Edit page

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/SurveyController.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/enums/ProgramValidation.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/ProgramRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyEditService.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/ATRCDepthValidationTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/ATRCMethod7BlockCheckTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/ATRCMethodCheckIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/BeforeDateCheckTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/Block0DataCheckTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/DebrisZeroObsTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/DirectionDataCheckTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/DiverExistsIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/DuplicateRowCheckTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/MeasureJsonValidationTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/Method3QuadratMax50Test.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/MissingDataCheckTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/NoSpeciesFoundMeasurementsTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/ObservableItemExistsIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/RLSDepthValidationTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/SpeciesBelongToMethodCheckTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/SpeciesSupersededTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/SurveyAtSiteTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/TotalCheckSumTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcessIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcessTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/ZeroInvertsTest.java
db/schema-update/15-add-frdc-program.sql
db/schema-update/16-add-frdc-program.sql

Commits [93f6e4a](https://github.com/aodn/nrmn-application/pull/1106/commits/93f6e4aee2dc1216b5a5c58b6420d0748e4a3046) and [9d28911](https://github.com/aodn/nrmn-application/pull/1106/commits/9d28911affa63982d6f5af0c905a7da3cf6089cc) contain the work to add the FRDC program and have it validate using ATRC rules. This filter will show just these commits: https://github.com/aodn/nrmn-application/pull/1106/files/9d28911affa63982d6f5af0c905a7da3cf6089cc.
Subsequent commits are refactoring the way the program is passed to the validation methods, as well as reformat the ValidationProcess class to make use of the Java 11 `var`.

Add FRDC Program

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/SurveyController.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SurveyRepository.java

Improve the speed of diver query

Improve diver search speed

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/SurveyController.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SurveyRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/dynamicQuery/FilterCondition.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/dynamicQuery/SurveyFilterCondition.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyCorrectionService.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/SurveyControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/model/db/SurveyTestData.java
web/src/components/import/DataSheetView.js
web/src/components/import/panel/FindReplacePanel.js
web/src/components/job/JobList.js
web/src/components/job/JobView.js

- Show sheet icon in Job List for Ingested as well as Staged sheets
- Display original datasheet as read-only for ingested jobs
- Add to datasheet from Job View page
- Fix the S3 download link in the Job View page
Also remove some unused vars and fix compiler type warnings.

View source data sheet for ingested jobs

---

.vscode/launch.json
web/src/components/data-entities/survey/SurveyCorrect.js
web/src/components/data-entities/survey/panel/SummaryPanel.js
web/src/components/import/DataSheetEventHandlers.js
web/src/components/import/DataSheetView.js
web/src/components/import/__test__/DataSheetView.test.tsx

Implement Find / Replace and Clone / Delete row and error highlighting as the same as the ingestion sheet.
Filter and go to value when clicking a validation.
Also update tests and VSCode launch configuration.

Implement editing customisations for Corrections sheets

---

web/src/components/import/DataSheetView.js

Fix 'Save' overlay not appearing after first save when editing and ingest sheet.

Fix 'Save' overlay not appearing after first save

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/DiverController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/LocationController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/ObservableItemController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/SiteController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/TemplateController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/exception/ResourceNotFoundException.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/exception/ValidationException.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/ObservableItemDtoMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/ObservableItemPutDtoMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/SiteDtoMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/StagedRowFormattedMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/security/JwtAuthenticationEntryPoint.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyEditService.java

Found the following unchecked Exceptions:
au.org.aodn.nrmn.restapi.controller.exception.ResourceNotFoundException
au.org.aodn.nrmn.restapi.controller.exception.ValidationException
software.amazon.awssdk.core.exception.SdkClientException
software.amazon.awssdk.services.s3.model.NoSuchKeyException
org.springframework.security.core.userdetails.UsernameNotFoundException
java.time.format.DateTimeParseException
java.time.format.DateTimeParseException
au.org.aodn.nrmn.restapi.security.RequestRejectedException
A few of it will print log entry
| Log level | Message |
|------ | ------- |
| Error | Ingestion Failed |
| Error | Could not download original file for job %s. %s" | 
| Error |  key "%s" does not exist in bucket "%s". Could not download original file for job %s| 
| Error |  Could not set …

Make sure exception appears in log for sumologic

---

web/src/components/data-entities/survey/SurveyCorrect.js

Adds to the corrections confirmation page a list of every change made to the corrections sheet prior to submitting.

Survey Corrections Summary Feature

---

web/src/components/data-entities/diver/__test__/DiverList.filter.test.tsx
web/src/components/data-entities/location/__test__/LocationList.filter.test.tsx
web/src/components/data-entities/observable-item/__test__/ObservableItemList.filter.test.tsx
web/src/components/data-entities/site/__test__/SiteList.filter.test.tsx
web/src/components/data-entities/survey/__test__/SurveyList.filter.test.tsx
web/src/components/job/__test__/JobList.filter.test.tsx

Disables flakey Jest tests until fixed in https://github.com/aodn/backlog/issues/4455

Disable flaky Jest tests

---

api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/CorrectionRowRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/ObservationRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/SurveyMethodRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/correction/CorrectionRowDto.java
web/src/components/data-entities/survey/SurveyCorrect.js
web/src/components/import/DataSheetView.js

Changes made the corrections sheet:
- Remove M6 and M13 observations from corrections rows.
- Coalese observations into the same row when otherwise a duplicate
- Add Total column
Also fixes the regression with the ingest sheet filters.
Available for testing at http://nrmn-aodnstack-nsp.dev.aodn.org.au.
To compare datasheets:
http://nrmn-aodnstack-nsp.dev.aodn.org.au/data/survey/6002304/correct
http://nrmn-edge.aodn.org.au/data/survey/6002304/correct

Corrections Feedback 1

---

web/src/components/data-entities/diver/DiverList.js
web/src/components/data-entities/location/LocationList.js
web/src/components/data-entities/observable-item/ObservableItemList.js
web/src/components/data-entities/site/SiteList.js
web/src/components/data-entities/survey/SurveyCorrect.js
web/src/components/data-entities/survey/SurveyList.js
web/src/components/import/DataSheetView.js
web/src/components/job/JobList.js

This disables the "drag to remove" column feature of Aggrid.

Aggrid: Lock column visibility

---

api/src/main/java/au/org/aodn/nrmn/restapi/data/model/StagedRow.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/CorrectionRowRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/correction/CorrectionRowDto.java
web/src/components/data-entities/survey/SurveyCorrect.js

Also remove observation ids which are no longer used

Fix correction row measurement grouping

---

web/src/components/data-entities/survey/SurveyList.js

Also add a button that opens a corrections sheet from the selected surveys.

Add multi row selection to Survey list

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyEditService.java

This bug prevents editing of survey 812326584 and others.

Survey edit: Handle missing survey time

---

web/src/components/data-entities/survey/SurveyCorrect.js

- Fix deleted rows always showing as 'row 0'
- Display measurements if changed
- Format as table and use header name in messages instead of field

Improve survey corrections feedback summary

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/CorrectionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/ObservableItemRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/BoundingBoxDto.java
web/src/components/data-entities/survey/SpeciesCorrect.js
web/src/components/data-entities/survey/SpeciesCorrectFilter.js

Use the coordinates from the survey if available, otherwise use the site.

Species correction bounding box filter

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/CorrectionController.java
web/src/components/data-entities/survey/SurveyCorrect.js

Job titles are fixed at 255 characters in the DB.
Also disable export button (for now)

Fix corrections job reference length

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/CorrectionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/SurveyController.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/ObservableItemRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/SurveyRepository.java
web/src/components/data-entities/survey/SpeciesCorrect.js
web/src/components/data-entities/survey/SpeciesCorrectFilter.js
web/src/components/input/CustomSearchInput.js

Also display the locations associated with the filter at the top of the correction pane, similar to the Template Export screen.

Species Correct: Add EcoRegion Filter

---

web/src/components/data-entities/survey/SpeciesCorrect.js

- move location chips to below form
- hide results table on load
- fix warning due to tablecell not being within a tablerow

Species Correction: Minor UI improvements

---

api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/ObservableItemRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/SiteRepository.java
web/src/components/data-entities/survey/SpeciesCorrect.js
web/src/components/data-entities/survey/SpeciesCorrectResults.js

- Refactor SpeciesCorrect into different components.
- Add missing `@Param` annotation to repository method signatures.

Minor code improvements

---

api/src/main/java/au/org/aodn/nrmn/restapi/data/model/SurveyListView.java
web/src/components/data-entities/survey/SurveyList.js

HasPQs should only be true if `pq_catalogued` is true, not if it is not null.

Fix Survey List HasPQs

---

web/src/components/data-entities/survey/SurveyCorrect.js
web/src/components/data-entities/survey/SurveyMeasurementHeader.js
web/src/components/data-entities/survey/panel/SurveyCorrectPanel.js
web/src/components/import/DataSheetEventHandlers.js

- Export entire sheet using the button
- Export a region by Shift-clicking and right-click "Export & Delete"

Survey corrections export

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/DataValidation.java
api/src/test/java/au/org/aodn/nrmn/restapi/integration/RLSMethodCheckIT.java
api/src/test/resources/testdata/FILL_DATA.sql
db/schema-update/19-m12-debris-species.sql

Allow M12 on ingest and corrections
Require M12 to be Debris recorded on block 2

Support Debris Method 12

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/SurveyValidation.java
api/src/test/java/au/org/aodn/nrmn/restapi/integration/RLSMethodBlockAssociationIT.java

- Check that M10 has Block 1 and Block 2
- When validating species treat all M1 species as valid for M10

Support Historical Method 10

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/CorrectionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/DataValidation.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/SurveyValidation.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/integration/ATRCMethodCheckIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/data/ATRCMethod11Block0Test.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/SpeciesBelongToMethodCheckTest.java
api/src/test/resources/testdata/FILL_DATA.sql
db/schema-update/20-m11-historical-species.sql

Corrections validation only. M11 on ingest will throw a blocking error.
ATRC program validation (FRDC and ATRC programs)
Only allowed for the species:
- Haliotis rubra
- Jasus edwardsii
- Jasus verreauxi (superseded by Sagmariasus verreauxi)

Support Historical Method 11

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/MaterializedViewService.java
db/schema-update/18-none-program.sql
web/src/components/data-entities/survey/SpeciesCorrectFilter.js
web/src/components/data-entities/survey/SurveyCorrect.js
web/src/components/data-entities/survey/SurveyEdit.js
web/src/components/data-entities/survey/SurveyList.js
web/src/components/job/JobView.js

Implement misc feedback:
- survey: rename screens specify either 'survey metadata' or 'survey data'
- species correct filter: update default dates to min 1/1/1996, max today
- job view: hide program and extended if no program
- db: use empty name for null program instead of "NONE"
- make the materialised view refresh less chatty in the logs + add timings

Misc fixes

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/DataValidation.java
api/src/test/java/au/org/aodn/nrmn/restapi/integration/ValidationProcessIT.java
web/src/components/data-entities/survey/panel/SurveyCorrectPanel.js

Prevents all the rows in a job from being deleted.

Blocking validation if row data missing

---

api/src/main/java/au/org/aodn/nrmn/restapi/data/model/DiverMethodAggregateView.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/model/SurveyListView.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/SurveyListRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/dynamicQuery/SurveyFilterCondition.java

No change in UI, speed up for general case, but poor performance remain if user search the diver name or method field.

4560 survey speedup

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/CorrectionController.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/AuthControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/CorrectionsControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/IngestionControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/utils/RequestWrapper.java
api/src/test/resources/testdata/FILL_DATA.sql
api/src/test/resources/testdata/testlayer.kml

Just implemented some of the test cases

4415 improve test coverage

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/SharedLinkController.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/MaterializedViewService.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/ScheduledTasks.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/upload/S3IO.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/upload/SharedLinkService.java
web/src/components/data-entities/shared-link/SharedLinkList.js

- Expires shared links and deletes S3 artifacts as part of the scheduled tasks
- Also prevent setting the expiry to before tomorrow's date in UI
- Refactors link creation + expiry into a service

Add Link Expiry to Scheduled Tasks

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/AuthController.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/model/SecUser.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/auth/LoginRequest.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/payload/JwtAuthenticationResponse.java
api/src/main/resources/sql/application.sql
api/src/test/java/au/org/aodn/nrmn/restapi/controller/AuthControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/CorrectionsControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/IngestionControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/utils/RequestWrapper.java
api/src/test/resources/testdata/TEST_USER.sql
db/schema-update/03-add-secuser-passwd-reset-flag.sql
web/src/App.js
web/src/api/api.js
web/src/components/auth/ChangePasswordForm.js
web/src/components/auth/LoginForm.js
web/src/components/layout/AuthState.js

Adds a user menu that is displayed when the user email is clicked, with options to Change Password or Logout.
Change Password will change user password provided it is at least 8 characters and then immediately log out.
The `expires` field has been added to the `sec_user` table. When set to a date in the past the user will be redirected to the Change Password page and cannot proceed until the password has been updated.
Please ensure that `03-add-secuser-passwd-reset-flag.sql` has been applied before merging.

Change Password Feature

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/CorrectionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyCorrectionService.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/SurveyValidation.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/CorrectionsControllerIT.java
web/src/components/data-entities/survey/SurveyCorrect.js
web/src/components/ui/ApplicationError.js

Adding or removing surveys in a corrections sheet should not be allowed.
- Survey Deletion should happen on the Survey Edit page
- Survey Creation should happen during Job Ingest.

Validate that survey IDs match corrected rows

---

.vscode/launch.json
api/src/main/java/au/org/aodn/nrmn/restapi/controller/SharedLinkController.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/MaterializedViewsRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/sharedlink/SharedLinkPutDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/CSVFilterPrinter.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/MaterializedViewService.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/ScheduledTasks.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/upload/SharedLinkService.java
web/src/App.js
web/src/components/data-entities/shared-link/SharedLinkAdd.js
web/src/components/data-entities/shared-link/SharedLinkList.js
web/src/components/ui/ApplicationError.js
web/src/index.css

- Implement `ep_m1` and `ep_m2_cryptic_fish` CSV exports for all, australia and states filters.
- Add the ability to generate more than one link at a time.
- Also improve CSS for Firefox and adds a Firefox debugging target for VSCode

Add Shared Link CSVs + Improve UI

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/CorrectionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/IngestionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/SurveyController.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/model/SharedLink.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/MaterializedViewService.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/ScheduledTasks.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/upload/S3IO.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/upload/SharedLinkService.java
db/schema-update/02-link-table.sql

Do all daily scheduled tasks in the following order:
- Refresh all materialized views
- Expired shared links
- Export csv to staging bucket on S3, then
- Copy over shared link files with updated CSVs

Update Shared Links Daily

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/SharedLinkController.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/sharedlink/SharedLinkDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/MaterializedViewService.java
web/src/components/data-entities/shared-link/SharedLinkAdd.js
web/src/components/data-entities/shared-link/SharedLinkList.js

- Also sort by created date by default and after adding a link
- Improve button feedback
- Show created time
- Fix filter icons which were wrong way around

Fix shared link CSV filename

---

.vscode/launch.json
web/src/components/auth/LoginForm.js
web/src/components/data-entities/diver/DiverList.js
web/src/components/data-entities/location/LocationAdd.js
web/src/components/data-entities/location/LocationList.js
web/src/components/data-entities/location/LocationView.js
web/src/components/data-entities/observable-item/ObservableItemAdd.js
web/src/components/data-entities/observable-item/ObservableItemEdit.js
web/src/components/data-entities/observable-item/ObservableItemList.js
web/src/components/data-entities/observable-item/ObservableItemView.js
web/src/components/data-entities/shared-link/SharedLinkAdd.js
web/src/components/data-entities/shared-link/SharedLinkList.js
web/src/components/data-entities/site/SiteEdit.js
web/src/components/data-entities/site/SiteList.js
web/src/components/data-entities/site/SiteView.js
web/src/components/data-entities/survey/SpeciesCorrect.js
web/src/components/data-entities/survey/SurveyCorrect.js
web/src/components/data-entities/survey/SurveyEdit.js
web/src/components/data-entities/survey/SurveyList.js
web/src/components/data-entities/survey/SurveyView.js
web/src/components/datasheets/ExtractTemplateData.js
web/src/components/import/DataSheetView.js
web/src/components/import/JobUpload.js
web/src/components/job/JobList.js
web/src/components/job/JobView.js
web/src/components/layout/Homepage.js
web/src/components/layout/SideMenu.js

Every browser tab should now have the same title as the main header on the page. This makes opening multiple tabs much less confusing.

Add browser titles

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/DiverController.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/model/Diver.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/DiverService.java
api/src/main/resources/sql/application.sql
api/src/test/java/au/org/aodn/nrmn/restapi/service/DiverServiceTest.java
db/schema-update/04-add-diver-created.sql
web/src/components/data-entities/diver/DiverList.js

Add a delete button to the Diver List to delete any diver created less than 24 hours ago that has no associated observations.

Diver Deletion

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/CorrectionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/DiverController.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/correction/CorrectionRequestBodyDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyCorrectionService.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/CorrectionsControllerIT.java
web/src/components/data-entities/survey/SurveyCorrect.js
web/src/components/data-entities/survey/panel/SurveyCorrectPanel.js

- Always validation and ingest corrections sheets as extended sized.
- Fix invert size formatting on corrections summary page.

Fix correction invert size validation

---

web/src/components/data-entities/survey/SurveyCorrect.js

- show diff for all fields
- hide toolbar when summary displayed

improvement survey corrections summary

---

web/src/components/data-entities/shared-link/SharedLinkList.js

Reverts aodn/nrmn-application#1225

Revert "Display Shared Link List dates in local timezone"

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/IngestionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/StagedJobController.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/model/GlobalLock.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/GlobalLockRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/GlobalLockService.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/ScheduledTasks.java
api/src/main/resources/sql/application.sql
db/schema-update/06-global-lock.sql
web/src/components/import/DataSheetView.js

- add global lock table to schema
- add global lock service
- wrap validation and ingest with lock
- remove all locks on application startup
- web: display an error if request fails

Global Ingestion Lock

---

api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/MaterializedViewsRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/MaterializedViewService.java

Replaces ep_species_survey which wasn't on the list.

Add ep_species_survey_observation to Shared Link

---

db/schema-update/05-add-geom-indices.sql

this appears to speed up the meow ecoregion check by a few seconds.

Add geom indexes

---

web/src/components/data-entities/survey/SurveyList.js

Hide duplicate survey ID in survey list

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/AdminController.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/ScheduledTasks.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/ValidationProcess.java
web/src/App.js
web/src/api/api.js
web/src/components/layout/AuthState.js

Allow admin users to manually initiate startup and daily tasks.

Implement Admin functions

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/CorrectionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/model/StagedJobLog.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/ObservationRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/enums/StagedJobEventType.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/StagedRowFormatted.java
api/src/main/resources/sql/application.sql
api/src/test/java/au/org/aodn/nrmn/restapi/controller/CorrectionsControllerIT.java
db/schema-update/01-add-staged-log-surveyid-summary.sql
web/src/components/data-entities/survey/SurveyCorrect.js
web/src/components/job/JobView.js

Store the diff in a JSONB column on the stage job.
Schema update has been applied to the `nrmn_dev` DB.
Replaces https://github.com/aodn/nrmn-application/pull/1242.

Add Corrections Summary to Staged Log

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyCorrectionService.java

Diver and Inverts are filled in by the UI and query respectively, since these values are not store for SND rows.

Exclude SND auto-filled values from corrections diff

---

.vscode/launch.json
api/src/main/java/au/org/aodn/nrmn/restapi/controller/CorrectionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/model/Site.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/correction/SpeciesCorrectResultBodyDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/correction/SpeciesCorrectResultDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/survey/SurveyListDto.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/CorrectionsControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/utils/RequestWrapper.java
web/src/components/data-entities/survey/__test__/SpeciesCorrect.species404Error.json

- Improve API Types by using DTOs instead of ad-hoc maps
- Move VSCode environment variables to `.env.development.local`

Code and project improvements

---

web/src/components/data-entities/survey/SurveyEdit.js

Allow the survey program to be changed from FRDC to ATRC and ATRC to FRDC.

Allow Survey Program to be changed between FRDC and ATRC 

---

.github/workflows/maven.yml

Cancels any existing builds for a branch when a new commit is pushed.

Cancel in-progress CI builds

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/AdminController.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/model/SecUser.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/auth/SecUserDto.java
web/src/App.js
web/src/components/admin/UserComponent.js
web/src/components/admin/UserList.js
web/src/components/data-entities/shared-link/SharedLinkList.js
web/src/components/input/TargetUrlComponent.js
web/src/components/layout/AuthState.js
web/src/index.css

For users with the Admin role this will display a list of users with the following functions:
- Add New User will create a new user with the ROLE_DATA_OFFICER and assign a random password that must be changed on first login.
- Edit will change the user email or full name.
- Disable Account will prevent the user from logging in next time but removing all user roles and setting account status to DEACTIVATED.
- Reset Password will assign a random password that must be changed on first login.
- Enable Admin will give user access to the admin options from the user menu (toggles the ROLE_ADMIN). Admin users will appear highlighted in yellow.

User management functions

---

.github/workflows/maven.yml
Dockerfile.build

This workflow can be used as a template to migrate other Jenkins pipelines to GitHub Actions.

Build artifact in a Docker container

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyCorrectionService.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/formatting/ColumnNameFormattingService.java

Show the invert or fish size as the column name in the survey diff.

Format measurement column names in survey diff

---

web/src/common/constants.js
web/src/components/data-entities/survey/SurveyCorrect.js
web/src/components/data-entities/survey/SurveyList.js
web/src/components/import/DataSheetView.js

And add delay on apply filters

Resize column to make it more visible

---

db/endpoints/CreatePrivateEndpoints.sql

resolves https://github.com/aodn/nrmn-application/issues/1280

remove condition in ep_species_list to exclude superseded species

---

db/pg_cron/nrmn_cron.sql
db/pg_cron/readme

need somewhere to put the pg_cron sql code for NRMN 
see [convert existing cron jobs to pg_cron](https://github.com/aodn/backlog/issues/4881)

pg_cron sql scripts for nrmn

---

db/data-update/PQCategoryNameUpdate/CategoryUpdate.sql

related to https://github.com/aodn/nrmn-application/issues/1139

#1139 Update category and major category

---

db/schema/CreateMiscAncillaryObjects.sql

You will not be able to run the sql from intellj which is intended. Please use psql and execute the sql from the same folder as CreateMiscAncillaryObjects.sql

Add execution line and for it to run with pgsql

---

web/src/api/api.js

bug fixing for the upgraded axios package. Now all the headers must be explicitly showed in 'config' parameter.

bug fixing for the upgraded axios

---

web/package.json
web/src/components/data-entities/observable-item/ObservableItemAdd.js
web/src/components/data-entities/survey/SpeciesCorrectEdit.js
web/src/components/data-entities/survey/SpeciesCorrectErrorResults.js
web/src/components/data-entities/survey/SpeciesCorrectResults.js
web/src/components/data-entities/survey/SurveyDiff.js
web/src/components/data-entities/survey/SurveyList.js
web/src/components/datasheets/GridHeader.js
web/src/components/import/custom/header.js
web/src/components/input/CustomAutoCompleteInput.js
web/src/components/layout/Homepage.js
web/src/components/search/SpeciesSearch.js
web/yarn.lock

Remove all usage of mui/styles, and use "styled" and 'sx' to instead.

replace usage of @mui styles version2#5224

---

web/src/components/data-entities/survey/SpeciesCorrectEdit.js
web/src/components/data-entities/survey/SpeciesCorrectErrorResults.js
web/src/components/data-entities/survey/SpeciesCorrectResults.js
web/src/components/data-entities/survey/SurveyDiff.js
web/src/components/datasheets/GridHeader.js
web/src/components/import/custom/header.js

Format changes. Inline extracted variables.

---

api/src/main/java/au/org/aodn/nrmn/restapi/config/ForkJoinConfig.java

Change ForkJoin default core from N-1 to N

Override cores default of ForkJoin
