Jenkinsfile

Apparently the workspace for a branch build is shared which causes all sorts of problems.  Thanks @lwgordonimos

Fixes aodn/backlog#2345 - disable concurrent branch builds

---

Jenkinsfile
ui/pom.xml

* use jenkins global yarn cache to speed up builds
* leave node_modules alone when cleaning workspace 
* use more recent version of yarn
* lock package versions selected for consistent builds

Fix various build issues

---

api/src/main/java/au/org/aodn/nrmn/restapi/model/db/audit/UserActionAudit.java

Noticed that where the UserActionAudit is being called we've been using the constructor that doesn't take an Authentication object, which means that user isn't being stored. This change makes that constructor try to retrieve authentication from the context (```getContext()``` is guaranteed to never return null).

Make UserActionAudit constructor get auth details itself

---

api/src/main/java/au/org/aodn/nrmn/restapi/config/WebMvcConfig.java

not just ones ending in a slash (eg, .csv ones)

Make global interceptor work for all api paths

---

api/src/main/java/au/org/aodn/nrmn/restapi/model/db/ObservableItem.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/Site.java
api/src/test/java/au/org/aodn/nrmn/restapi/model/db/SiteTestData.java

Adding a title breaks react json-schema forms - it uses it for all key names.  Also, siteAttribute must be a <String, String>Map to be rendered properly.
Before:
After:
Can't see anyway of specifying a title at the moment.  Still looking...

Fix display of site/observable items attributes

---

api/src/main/java/au/org/aodn/nrmn/restapi/model/db/SecUser.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/StagedJobLog.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/StagedRow.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/StagedRowRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/model/db/SecUserTestData.java
api/src/test/java/au/org/aodn/nrmn/restapi/model/db/StagedJobIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/model/db/StagedJobLogIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/model/db/StagedJobTestData.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcessIT.java

Validation process was looking up associated rows by reference (file name) so all rows uploaded for that reference (file name) were being included in validation including ones from other jobs.
Also fixed some issues with Integration tests.

Fix duplicates being returned when validating jobs

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/DiverRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SiteRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/requestcache/InvocationTarget.java
api/src/main/java/au/org/aodn/nrmn/restapi/requestcache/RequestCache.java
api/src/main/java/au/org/aodn/nrmn/restapi/requestcache/RequestCacheManager.java
api/src/main/java/au/org/aodn/nrmn/restapi/requestcache/RequestScopeAspect.java

As per https://okraskat.github.io/caching-per-request-with-spring/
Improves validation performance  for https://github.com/aodn/backlog/issues/2661
Added for Diver and Site only - not expecting any improvement for species.

Cache findbycriteria responses made in a request

---

api/pom.xml
api/src/main/java/au/org/aodn/nrmn/restapi/validation/springdatarest/BeforeCreateLocationValidator.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/springdatarest/BeforeCreateSiteValidator.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/springdatarest/BeforeSaveSiteValidator.java
api/src/test/java/au/org/aodn/nrmn/restapi/test/PostgresqlContainerExtension.java

- Upgrade to a recent version of testcontainers containing a fix for a recent issue pulling test containers from docker repository.
- Trap and report errors thrown when starting up the postgres test container.  We want tests to fail if the container doesn't startup instead of silently skipping them.
- Fix broken tests not picked up because of these issues.

Fix issue running integration tests in github actions

---

api/src/main/java/au/org/aodn/nrmn/restapi/model/db/Location.java

Refer https://github.com/aodn/backlog/issues/2710
Can't get this to show in the UI at the moment which is good, but has been a problem in the past.

location isActive should not be null

---

api/pom.xml
api/src/main/java/au/org/aodn/nrmn/restapi/config/MappingConfig.java

Upgraded ModelMapper from 2.3.0 to 2.3.3 so to use the option to disable collection merge behaviour.

Fix Site > OldSiteCodes not removing or updating correctly

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/AuthController.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SecUserRepository.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/AuthControllerIT.java
api/src/test/resources/testdata/TEST_USER.sql

Remove blacklisted token when logging in if the same token is generated again.
Use a separate user for authorisation controller tests - prevents issues using that user again within the same second in subsequent tests - see aodn/backlog#2806.
In future we could actually login instead of just generating a token to better test actual authentication and authorisation during tests.

Fixes aodn/backlog#2806

---

ui/src/components/data-entities/EntityContainer.js
ui/src/components/data-entities/EntityEdit.js
ui/src/components/search/SpeciesSearch.js

Superseded species names appear slightly greyer to other search results and clicking them will not autofill the form but display a warning containing the superseded name. 
Switched the order of the NRMN and WoRMS search so that WoRMS is now the default.
Also made the search component much wider and taller to avoid scrolling.

Indicate if species superseded in species search

---

api/src/test/java/au/org/aodn/nrmn/restapi/service/WormsServiceIT.java

We shouldn't fail builds because external service is down
```
[INFO] Running au.org.aodn.nrmn.restapi.service.WormsServiceIT
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 s - in au.org.aodn.nrmn.restapi.service.WormsServiceIT
```

Disable WormsService test

---

ui/src/components/data-entities/EntityEdit.js
ui/src/components/data-entities/customWidgetFields/SearchInput.js

Prevents the supersededBy field from autocompleting with the same observable item name.
http://nrmn-fix-circular-autocomplete.dev.aodn.org.au/

Observable Item Edit: Prevent circular supersededby

---

ui/src/components/data-entities/form-reducer.js

Remove the genus from the species to autofill the species epithet for new observable items.

Fix species epithet in WoRMS search results

---

ui/src/components/search/SpeciesSearch.js

By default, just selecting the species and using 'ctrl-c' keyboard shortcut will select and copy the entire row.
Stack available at http://nrmn-fix-species-search-copy-paste.dev.aodn.org.au

Species search: Prevent ctrl-c from highlighting and copying the entire row.

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/SpeciesController.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/WormsService.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/WormsServiceIT.java

Restricted by functionality available in worms.  Page size is set to 50 and we can't get total number of matching records.

Add limited paging to worms/nrmn search

---

api/src/main/java/au/org/aodn/nrmn/restapi/dto/species/SpeciesDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/WormsService.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/model/SpeciesRecord.java
ui/src/components/search/SpeciesSearch.js

Lookup each WORMS result species name against the NRMN observable item database. Add a column to the search result to show true/false if there is already an NRMN record with the same species name.
Also adds an event handler to search when pressing return.
Stack: http://nrmn-nrmn-worms-lookup.dev.aodn.org.au/

Show if WORMs search result already exists in NRMN database

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/main/resources/application.properties
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java

Ingest by survey/survey method so that we only have to look up survey/survey method once
And don't use find by example for looking up measures as this doesn't use the cache.  FindById makes more sense anyway.
Need to revisit ingestion tests as they don't make sense now after refactoring.

aodn/backlog#3042  - Speed up ingestion

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/SiteController.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SiteRepository.java

Sort list by site code by sorting the alpha part alphabetically followed by the numeric part sorted lowest to highest.
Stack deployed to http://nrmn-site-list-order.dev.aodn.org.au

Improve Site list ordering

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java

The inverts total should be included as an unsized  fish size or invert size measure for method 1 and 2 dependent on extended size/use invert sizing flags as per other measures for these methods or as a single item count for debris.  It doesn't apply for other methods/types of items.

Include unsized invert observations when ingesting staged job

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyContentsHandler.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SpreadSheetServiceIT.java

Its not maintained or displayed in the front end.  Just use the inverts column which is.

aodn/backlog#3107 - don't store inverts in measures as well as inverts column

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/row/formatted/MeasureBetweenL5l95.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/row/formatted/MeasureUnderLmax.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/formatted/MeasureBetweenL5l95Test.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/validators/formatted/MeasureUnderLmaxTest.java

Do not validated species sizing when L5-L95 and Lmax are zero or null

Unsized species validation

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/global/formatted/Method3QuadratsMissing.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/global/formatted/Method3QuadratsSum.java

Backlog item: https://github.com/aodn/backlog/issues/3125
Updates error message from `Transect: 10.1-BI-S1-17976 quadrats sum under 50`
to
`Transect: BI-S1-2019-03-21-10.1 quadrats sum under 50.`

Update m3 transect quadrat sum error messages

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/base/BaseGlobalFormattedValidator.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/global/formatted/DuplicateRowCheck.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/global/formatted/Method3QuadratsMissing.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/validators/global/formatted/Method3QuadratsSum.java
ui/src/components/import/DataSheetView.js
ui/src/components/import/panel/ValidationPanel.js

Improvement of work in https://github.com/aodn/backlog/issues/3168
@nspool This will make the Duplicate Rows Check include the rowId in the payload. This is the first step in highlighting the duplicated row. It requires front-end changes to match.
Global Error payload:
```json
{
"errorGlobal":[
{
"rowId":1500,
"jobId":14,
"message":"Row 99 may be a duplicate of row 98.",
"errorType":"GLOBAL",
"errorLevel":"WARNING",
"columnTarget":"Duplicates"
}
]
}
```

Include rowId in global error messages

---

ui/src/components/data-entities/EntityEdit.js
ui/src/components/data-entities/customWidgetFields/SearchInput.js

Backlog item: https://github.com/aodn/backlog/issues/3130
Clears after blur - The options remain filtered though, I could not find an appropriate hook to reset them.

Clear supersededBy when no option is selected

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/SurveyMethodRepository.java

Backlog item: https://github.com/aodn/backlog/issues/3038
See: https://github.com/aodn/backlog/issues/3038#issuecomment-884508298
Basically only show blocks & methods that have been completed to avoid duplicating information.

Only show blocks and method for surveys that have been completed

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/projections/SpeciesWithAttributesCsvRow.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/TemplateService.java

Fixes issue with download template data resulting in 500 error

Use primitive values to avoid nulls

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/ObservableItemController.java

Backlog item: https://github.com/aodn/backlog/issues/3130
This is a more unforgiving method of dealing with invalid/incomplete values.
The previous method would revert the value back to the previous `supersed_by` value if it existed. This method simply sets any invalid values to null.

Remove any invalid superseded value

---

ui/src/App.js
ui/src/components/auth/auth-reducer.js

Store the AG Grid license in local storage and set on page render. This is to prevent the grid from losing the license if the window is closed and opened again, or the page is refreshed.

AG Grid License: Persist between refreshes

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java

Fix 500 in validation in edge.  Happen when site has missing latitude or longitude.

Fix null pointer in validation

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/SiteRepository.java

Backlog item: https://github.com/aodn/backlog/issues/3323
@nspool is there a reason why we are referencing `ep_site_list` here. I can see that it may be filtered to sites that have locations and meow_ecoregions but I am not sure if that is a requirement for this. Also, I am not sure why this view is materialized considering it takes 1s to generate, unless its being referenced elsewhere and needs an index.

Changed validate to reference site_ref rather than materialized view

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/StagedRowFormattedMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/StagedRowFormatted.java

RLS depth may not have a survey number. Fall back to using zero as survey number.

Prevent null survey number

---

ui/src/components/data-entities/EntityEdit.js
ui/src/components/templates/SiteAddTemplate.js

Any validation errors will remove any added site codes from the form. There doesn't appear to be a way around this without reimplementing the generic UI "array of fields" function used for site codes.

Site add: allow old site codes

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/IngestionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/MaterializedViewsRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/MaterializedViewService.java
api/src/main/resources/sql/application.sql

Backlog item: https://github.com/aodn/backlog/issues/3234
When 5 tasks are running concurrently the following log output is produced. I have reformatted it to show how the concurrent tasks handle the views:
table_name | task1 | task2 | task3 | task4 | task5
-- | -- | -- | -- | -- | --
ui_species_attributes | refreshing ui_species_attributes | ui_species_attributes is already being refreshed | ui_species_attributes is already being refreshed | ui_species_attributes is already being refreshed | ui_species_attributes is already being refreshed
ep_m2_cryptic_fish | ep_m2_cryptic_fish is already being refreshed | refreshing ep_m2_cryptic_fish | ep_m2_cryptic_fish is already being refreshed | ep_m2_cryptic_fish is already being refreshed | ep_m2_cryptic_fish is already being refreshed …

Refresh materialized views on ingest

---

ui/src/components/import/DataSheetView.js

Backlog item: https://github.com/aodn/backlog/issues/3356
I think that given this is carving out a new exception on top of existing criteria this is safer than we originally thought

Delete row that is displaying the context menu

---

api/src/main/java/au/org/aodn/nrmn/restapi/model/db/StagedRow.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyContentsHandler.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/StagedRowFormatted.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SpreadSheetServiceIT.java
ui/src/components/import/panel/ValidationSummary.js

Remove ID check when staging surveys
Generate summaries based on staged input data. Previously it was only generating summaries from validated rows.
Implement additional ATRC M3 rules:
- ATRC Surveys must contain at least one row of M3
- Must also have at least one row with M3 and block 0

Go live fixes

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/StagedRowFormatted.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java

Should be by method / block combo, not surveynum / method.
Also remove the M12 override for debris observations.
Stack containing fix: http://nrmn-aodnstack-nspool.dev.aodn.org.au/home

Fix survey method assignment on ingest

---

api/src/main/java/au/org/aodn/nrmn/restapi/model/db/enums/ValidationLevel.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/StagedRowFormatted.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/DuplicateRowCheckTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/MissingDataCheckTest.java
ui/src/components/import/DataSheetView.js
ui/src/components/import/panel/ValidationPanel.js
ui/src/components/import/panel/ValidationSummary.js
ui/src/components/layout/SideMenu.js

- Require inverts to be an integer
- Show all duplicate rows numbers in tooltip and change highlight to blue
- If either species name or code match Debris Zero or Survey Not Found than validate row as such
- Use species name not code to determine SND and DEZ
- Display the build number under the version

Invert, Debris Zero and duplicate row validation improvements

---

api/pom.xml
api/src/main/java/au/org/aodn/nrmn/restapi/controller/StagedJobController.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
app/pom.xml
pom.xml
ui/pom.xml

Remove limit of 50 rows from duplicate validation
Remove RLS limit from Debris Zero check so it will apply to ATRC as well.

Remove limits from Debris Zero and Duplicate Row validations

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
scripts/db-update/04-lowercase_inside_marine_park.sql
ui/src/components/data-entities/EntityEdit.js

Migrated data stored the "inside marine park" value as 'Yes', 'No' or 'Unsure'. The API ingest code is storing as 'yes', 'no', or 'unsure'.
This PR changes the ingest to match the uppercase migrated values and includes a script to update previously edited values.

Fix lowercase inside_marine_park values

---

api/src/main/java/au/org/aodn/nrmn/restapi/dto/observableitem/ObservableItemDto.java
ui/src/components/data-entities/form-reducer.js

Only prefill from search if species does not contain spp. or parens.
Remove nonnull constraint and validation.

Species Epithet: Change search prefill behaviour and allow empty values

---

api/pom.xml

Necessary due to CVE-2021-44228.

Bump log4j version to 2.15.0

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/SurveyAtSiteTest.java
ui/src/components/data-entities/SiteEdit.js

- Datasheet: Display the coordinate validation if the distance between survey and site is greater than about 1m
- Site Clone: Show the coordinate validation warning immediately on page load instead of waiting for coords to be edited

Improve survey coordinate validation

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/DiverController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/StagedRowFormattedMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/DiverExistsIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/StagedRowFormattedMappingIT.java
api/src/test/resources/testdata/FILL_DATA.sql

Converts all datasheet diver names to ASCII before performing validations.
eg. if a datasheet contains "Juán Página" it will match successfully with "Juan Pagina" in the database.

Diver: Convert name to ASCII for validation and lookup

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyEditService.java
ui/src/components/data-entities/EntityEdit.js

Editing a survey with an empty PQ diver fills in the first diver from the DB since the field is not nullable.
Change so that the field can handle empty PQ divers and also remove an existing diver.

Survey Edit: Allow empty PQ diver

---

ui/src/components/import/DataSheetView.js
ui/src/components/import/panel/ValidationSummary.js

Removes the hack to hide spurious validation message and instead fixes the error tree generator to never group measurement warnings.

Never group measurement column validations

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/StagedRowFormattedMapperConfig.java

Both source and destination diver names need to be normalised before comparison.

Add source name normalisation to diver mapping

---

db/schema-update/14-add_mapped_id_db_trg.sql

Adds a Postgresql trigger to set the mapped_id to observable_item_id + 99900000.

Set mapped_id on observable item create

---

db/schema-update/14-add_mapped_id_db_trg.sql

Trigger is missing the nrmn schema prefix and is being added to the default schema.

Add missing schema name to mapped_id trigger

---

.gitattributes
api/src/main/java/au/org/aodn/nrmn/restapi/controller/LocationController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/TemplateController.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/LocationRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/projections/LocationExtendedMapping.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/TemplateService.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/TemplateServiceTest.java
ui/pom.xml
ui/src/components/data-entities/location/LocationList.js
ui/src/components/datasheets/ExtractTemplateData.js

- Change zip export API to only require location ID.
- Change location mapping so the UI can map all ecoregion,  country, area and site code to location ID.
- Change the UI to display a collection of locations for the intersection of eco region, country and area.
- Add a site code drop-down to add the associated location id to the displayed group of locations.
- Allow the user to pick some or all of the filtered locations and export an associated survey template zip.
Also adds a gitattributes filter containing test data file extensions to (potentially) speed up diffs.

Survey Template Export Narrowing Filter

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java

Still displaying and storing value as double since existing surveys have already been ingested with non-integer visibility values.

Survey visibility: Round to integer value

---

ui/src/components/job/JobList.js

Fix jobs not appearing in the list. Pagination is enabled and fixed at page size 20 on entities despite it not being supported in the UI. despite it not being supported in the UI.

U: Fix JobList page size to 99

---

web/package.json
web/yarn.lock

Dependabot is giving a security alert for this `react-scripts`. This package is only used for build so can be moved to depDependencies so there are no production security implications and the dependabot alert can be dismissed.
See also: https://stackoverflow.com/questions/71282206/github-dependabot-alert-inefficient-regular-expression-complexity-in-nth-check

Use react-scripts only as a dev dependency

---

db/schema/ApplyConstraints.sql
db/schema/BasicIndexing.sql
db/schema/CreateMiscAncillaryObjects.sql
db/schema/CreateTables.sql

This adds the `nrmn.` prefix to some db objects so that these scripts can be used with psql.

Add NRMN schema prefix to schema SQL

---

Jenkinsfile

Build is taking ~10 minutes longer than it should because Git is deleting and re-downloading the node_modules every time.

Update web project path in Jenkinsfile

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/test/PostgresqlContainerExtension.java

Survey validation should be displaying the distance from the site if greater than 10m.
I accidentally remove this from the message in the last PR.

Put back survey distance from site

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/LetterCodeRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/TemplateService.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/TemplateServiceTest.java

Generate the letter code map on a per-method basis to fix long letter codes.

Template Export: Filter by method before generating letter codes

---

web/src/components/import/DataSheetView.js
web/src/components/import/ValidationJob.js
web/src/components/import/panel/ValidationPanel.js
web/src/components/layout/AuthState.js

When removing Redux the isAdmin flag was changed temporarily to be a hardcoded boolean. This PR fixes this to use the AuthContext for checking roles.

Use auth context to determinal admin role instead of hardcoded flag

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java

Adding the prefix 'invert' will cause all invert measurement validations to be grouped as they are displayed alphabetically.

Add prefix to invert measurement validations

---

api/src/main/java/au/org/aodn/nrmn/restapi/validation/StagedRowFormatted.java
api/src/main/java/au/org/aodn/nrmn/restapi/validation/process/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/ATRCDepthValidationTest.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/ATRCSurveyGroupCompleteIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/RLSMethodBlockAssociationIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/RLSMethodCheckIT.java

Format the survey as "[site, date, depth.surveyNumber]" in the validation messages instead of just printing "site/date/depth".
This adds extra space to make it easier to read and also shows the survey number.

Print survey with decimal depth in validation messages

---

.gitignore
web/src/components/layout/SideMenu.js

Display version and features as a stack of Material UI chips instead of a a list of text labels.
Also add temporary files starting with `#` or `.#` to `.gitignore`.

Improve display of version and feature flags in side menu

---

web/src/components/data-entities/site/SiteList.js
web/src/components/data-entities/site/__test__/SiteList.test.tsx

Prevents the delete dialog from appearing when clicking an active site row in the 'delete' column. Also adds a Jest test for SiteList.

Site List: Disable delete handler for active sites

---

api/src/main/java/au/org/aodn/nrmn/restapi/model/db/StagedRow.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/ATRCSurveyGroupCompleteIT.java

Parse the row date and format consistently for the validations that use survey grouping.
Necessary since we are supporting multiple date formats.

Normalise date format before survey validation checks

---

web/src/App.js
web/src/components/data-entities/location/LocationList.js
web/src/components/data-entities/observable-item/ObservableItemList.js
web/src/components/data-entities/site/SiteList.js
web/src/components/search/SpeciesSearch.js

Add styles to the global theme and applies them to the Species Search table.
Also fixes console warning due to use of `min-width`. Replaces with the AgGrid column prop `minWidth`.

Add table styles and apply to species search to improve readability

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/TemplateService.java

Some versions of Excel apparently require this regardless of encoding. See: https://stackoverflow.com/questions/155097/microsoft-excel-mangles-diacritics-in-csv-files

Add Unicode byte order mark to template export diver CSV

---

web/src/components/import/panel/ValidationPanel.js
web/src/index.css

Fix the edit cell from being clipped by the filter row when there are only two rows in the grid. 
Also remove some obsolete props that were causing runtime warnings.

Reduce grid edit cell height

---

web/src/components/search/SpeciesSearch.js
web/src/components/search/__test__/SpeciesSearch.test.tsx

- Fix bug causing pagination to break when last page is less than maxPage size
- Update test to check the count in the footer (eg `1-50`) are correct

Fix Species Search pagination

---

.vscode/launch.json
web/src/components/data-entities/site/__test__/SiteList.test.tsx
web/src/components/import/__test__/DataSheetView.test.tsx
web/src/components/search/__test__/SpeciesSearch.test.tsx
web/src/components/ui/__test__/AlertDialog.test.tsx

Looping on the expect within await appears to sometimes fail. Fix so the await is in the innermost loop.
Also remove some unused imports and unneeded annotations.

Improve SiteList Test

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/WormsService.java

Split `(` and `[` checks into different capturing groups.

Fix potential ReDoS in WoRMS search regex

---

api/src/main/java/au/org/aodn/nrmn/restapi/tasks/ScheduledTasks.java
api/src/main/java/au/org/aodn/nrmn/restapi/util/LogInfo.java

Views are not being rematerialised in the scheduled task after the PQs are updated. This used to be done using a cron job on the DB server.
Also remove the ThreadContext calls from the logging since they refer to fields that are not being set.

Refresh materialised views after PQ update each night

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/StagedRowFormattedMapperConfig.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/StagedRowFormattedMappingIT.java

Block and Total values are using the default modelmapper mapping resulting in an unhandled exception when either value is not a number.
Fix found another bug where the Latitude and Longitude values were being returned as NaN instead of null if the conversion failed.
Add an invalid mappings test.

Add missing integer mappings for Block and Total columns

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/StagedRowFormattedMapperConfig.java
api/src/test/java/au/org/aodn/nrmn/restapi/validation/process/StagedRowFormattedMappingIT.java

If a size class has a value "0" then do not create an observation for that class (since nothing was observed!)

During ingest exclude observations with a zero count

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/SurveyController.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/ObservationRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SiteRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SurveyRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/projections/SurveyRow.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/projections/SurveyRowCacheable.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/projections/SurveyRowDivers.java

- Rewrite the Survey List native query as two cacheable HQL queries.
- Add missing Cacheable annotation to the Site `getAll` method.
Survey List query should now complete in about a second, down from ~10 seconds.

Speed up Survey and Site list queries

---

api/pom.xml
api/src/main/java/au/org/aodn/nrmn/restapi/config/RateLimitInterceptor.java
api/src/main/java/au/org/aodn/nrmn/restapi/config/WebMvcConfig.java
web/src/api/api.js

- Implements rate-limiting using bucket4j.
- Allow 20 auth requests every 10 minutes per IP address.
- When limit is reached display how long to wait until next attempt.

Implement rate-limiting on auth endpoint methods

---

api/src/main/java/au/org/aodn/nrmn/restapi/repository/ObservationRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyCorrectionService.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyCorrectionServiceTest.java
web/src/components/job/JobView.js

Instead of printing every single observation ID the log will now only record a range (unless the range is not contiguous).

Record modified IDs as a range on the correction job

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/CorrectionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/stage/StagedJobRowDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/enums/StatusJobType.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyCorrectionService.java
db/schema-update/16-update-job-status.sql
web/src/components/job/JobList.js

Change correction status from  "CORRECTION" to "CORRECTED" so that it matches the other job status types.
Requires a database update to be run after merge.

Rename correction job status from CORRECTION to CORRECTED

---

web/src/components/import/DataSheetView.js

When a filter is set, immediately change the filter to be the resulting row IDs so that if any row changes it will never disappear.
This trick is already used in the Clone Row function.

Always keep filtered rows in grid during edit

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/SiteController.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/Location.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/MeowEcoRegions.java
api/src/main/java/au/org/aodn/nrmn/restapi/model/db/Site.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/ObservationRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/SiteRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/dynamicQuery/FilterCondition.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/dynamicQuery/ObservationFilterCondition.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/dynamicQuery/SiteFilterCondition.java
api/src/main/java/au/org/aodn/nrmn/restapi/repository/dynamicQuery/SurveyFilterCondition.java
web/src/components/data-entities/location/LocationList.js
web/src/components/data-entities/observable-item/ObservableItemList.js
web/src/components/data-entities/site/SiteList.js

Reference data grid: use onBodyScrollEnd instead of onBodyScroll so that the grid is only sized once at the end of a scroll.
API: remove unused imports, annotate some raw types and add default case to switch statements that are missing.
~Site Entity: use a Lombok default builder for setting default value of isActive.~ 
Reverted change to the site entity since the original behaviour is correct, even though there is a warning.

Misc performance and code improvements

---

web/src/components/data-entities/survey/SurveyEdit.js
web/src/components/import/DataSheetEventHandlers.js

Survey Edit: use new paginated endpoint for autocomplete values
Datasheet: Set filter after edit only if filter previously set
Datasheet: Refresh cells after clone so that row numbers are updated
Datasheet: Clone the row measurements otherwise two rows point to the same values

Datasheet and Survey Edit fixes

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/CorrectionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/StagedRowMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/CorrectionRowRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/correction/CorrectionRowDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/StagedRowFormatted.java
web/src/components/data-entities/survey/SurveyCorrect.js

Add PQ diver to survey corrections sheet
Use the 'decimal depth' combining depth and survey number so the survey transect check can be reused.
Make the site/date/depth/id read-only until multiple surveys can be corrected.

Add PQ diver to survey corrections sheet

---

web/src/components/data-entities/survey/panel/SummaryPanel.js

Fixes issue where changing a cloned row to a different survey number causes validation to fail.

summary panel: skip mm header lookup if no column

---

web/src/components/import/DataSheetEventHandlers.js

Cleared fields should be assigned to empty values of the matching type, not just an empty string.
Only clear values that are editable.

datasheet insert row: ensure inserted row is deserializable

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/CorrectionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/SurveyController.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/model/Observation.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/model/SurveyMethodEntity.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/CorrectionRowRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/MeasureRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/SurveyMethodRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/correction/CorrectionRequestBodyDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/correction/CorrectionRowDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/correction/CorrectionRowsDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/enums/MeasureType.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyCorrectionService.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/SurveyValidation.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/ValidationProcess.java
api/src/main/resources/sql/application.sql
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyCorrectionServiceTest.java
db/schema-update/17-alter-seq-increment.sql
web/src/App.js
web/src/api/api.js
web/src/components/data-entities/survey/SurveyCorrect.js
web/src/components/import/DataSheetEventHandlers.js
web/src/components/job/JobView.js
web/src/components/ui/ApplicationError.js

Implements the ability to correct multiple surveys at once.
- Adds a 'Correct Job Surveys' button to the Job screen
- Add missing unvalidate columns to the corrections sheet so that the UI matches ingest
- Use batching for inserting observations and survey methods
- Refactor the MeasureType conversion from an inline switch to a static method
- Refactor the Application Error into a seperate component
- Update existing tests
Also rewrites the correction rows query which was not summing the observations when performing the row aggregate. So for identical rows with observations in the same size class only the first count was being returned instead of summing all the counts.
After merging this PR requires the script `db/schema-update/17-alter-seq-increment.sql` to be run on the DB otherwise …

Multiple Survey Corrections Feature

---

api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/CorrectionRowRepository.java

Change corrections rows to handle the latitude and longitude the same as the endpoints, by falling back to the site values if there are none on the survey.

Corrections: Display Site Latitude/Longitude if none on survey

---

web/src/components/data-entities/survey/SurveyCorrect.js
web/src/components/import/DataSheetEventHandlers.js

Measurements are stored as an object on corrections rows, but as a flat property on ingest rows. This PR adds a check to clone and update the measurement object (if present) so that undo works for measurement values in corrections.

Handle measurement undo for corrections sheet

---

web/src/components/import/DataSheetEventHandlers.js

Fixes a bug where after deleting a block of rows undo was only putting back a single row.

Fix datasheet undo after deleting multiple rows

---

api/src/main/java/au/org/aodn/nrmn/restapi/security/JwtTokenProvider.java
web/src/components/data-entities/survey/SurveyCorrect.js

If the same change has been made to multiple contiguous rows then display just one message with a range as the row value instead of a different message for each change.
Also log JWT expired token at Info not Error so it isn't reported by SumoLogic.

Group correction confirmation messages by group

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/CorrectionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/model/Survey.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/model/SurveyListView.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/SiteRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/survey/SurveyDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyCorrectionService.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/main/resources/sql/application.sql
api/src/test/java/au/org/aodn/nrmn/restapi/model/db/SurveyTestData.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyCorrectionServiceTest.java
db/schema-update/01-survey-lock.sql
web/src/components/data-entities/survey/SurveyEdit.js
web/src/components/data-entities/survey/SurveyList.js

- Add a boolean `locked` column to the `survey` table that if true will prevent any corrections being performed on survey data as well as prevent that survey from being deleted. 
- Set the value of this column to correspond to the output of @bpasquer's query from the backlog issue.
- For locked surveys hide the select checkbox in the Survey List to prevent the survey from being added to a corrections job
- Also display the message "Survey data are locked" on the Survey Metadata Edit page
- Update unit tests.

Survey Data Lock

---

db/schema-update/01-survey-lock.sql
web/src/components/data-entities/survey/SurveyEdit.js

- Fix update script as `NonStandardData` is a survey method attribute not an observable item attribute.
- Hide the locked data message from the Survey Edit page if the data is not locked.

Survey Lock Fixes

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/SurveyValidation.java
api/src/test/java/au/org/aodn/nrmn/restapi/integration/SurveyExistsIT.java

Survey Exists was previously ignored for M3. Now display as a warning and skip the survey completion check if it fails.

Display Survey Exists for M3 as warning

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/LocationController.java
api/src/test/java/au/org/aodn/nrmn/restapi/integration/ValidationProcessIT.java
web/src/components/data-entities/survey/SpeciesCorrect.js
web/src/components/data-entities/survey/SpeciesCorrectFilter.js
web/src/components/data-entities/survey/SurveyCorrect.js
web/src/components/datasheets/ExtractTemplateData.js

- Implements the same location filtering as the Export CSV Template filter. Locations matching the dropdown filters will appear as a set of buttons and can either be selected individually or added all at once to the filter.
- Added feature of only showing related EcoRegions/States/Areas in the filters. eg. if an Australian ecoregion is selected then only states and areas in that ecoregion will appear in the dropdowns.
- Show/Hide filter button which hides the filter when a survey search has commenced.
- Also adds and uses an optional `all` parameter to the `locations` endpoint to defeat pagination.

Add location narrowing to species correction filter

---

web/src/components/data-entities/survey/SpeciesCorrectFilter.js

`Add All Locations` is replacing the locations not appending them

Fix Add All Locations in species correct filter

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/ObservableItemController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/SpeciesController.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/model/SurveyListView.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/dynamicQuery/SurveyFilterCondition.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/ObservableItemControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/controller/SurveyControllerIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/model/db/ObservableItemIT.java
api/src/test/java/au/org/aodn/nrmn/restapi/model/db/ObservableItemTestData.java
api/src/test/java/au/org/aodn/nrmn/restapi/model/db/ObservationTestData.java
web/src/components/data-entities/survey/SurveyList.js

Run a bit faster now, from the explain plan, the most costly part is still the string_agg (for diver and method)
->  GroupAggregate  (cost=484002.59..520016.13 rows=29870 width=68)
"                                Output: sm.survey_id, string_agg(DISTINCT (sm.method_id)::text, ', '::text ORDER BY (sm.method_id)::text), string_agg(DISTINCT (dr.full_name)::text, ', '::text ORDER BY (dr.full_name)::text)"
Group Key: sm.survey_id
No species by default and hidden until you expand the filter. Max two species filter allowed

4512 improve performance

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/SurveyValidation.java

If M11 is allowed (ATRC corrections only) skip method check on M11 rows Otherwise validate based on species methods.

Fix M11 validation

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/upload/S3IO.java

Also set the expiry time on the object for 24 hours since that's when it will be copied over again.

Apply correct ACL to updated shared endpoint CSV

---

Jenkinsfile
web/pom.xml

Tests are run in GitHub actions so there's no need to run them on Jenkins also.
May also help reduce memory usage.

Skip tests when building on Jenkins

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/MaterializedViewService.java

`ep_site_list.csv` is being exported as `ep_site_list_all.csv`

Fix filename for unfiltered CSV shared links

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/CorrectionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/model/StagedJobLog.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/repository/ObservationRepository.java
api/src/main/java/au/org/aodn/nrmn/restapi/dto/correction/SpeciesCorrectBodyDto.java
api/src/main/java/au/org/aodn/nrmn/restapi/enums/StagedJobEventType.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyCorrectionService.java
api/src/main/resources/sql/application.sql
db/schema-update/01-add-staged-log-surveyid-summary.sql
web/src/components/data-entities/survey/SpeciesCorrectEdit.js
web/src/components/job/JobView.js

- Extend the StagedJobLog to include filters
- Also log the count of the observations changes
- Display the filters in a basic format if present on the job.

Store bulk species update filters

---

.vscode/tasks.json
web/src/components/data-entities/survey/SpeciesCorrectErrorResults.js
web/src/components/data-entities/survey/SurveyCorrect.js
web/src/components/import/DataSheetEventHandlers.js
web/src/components/import/DataSheetView.js

When copying a species name from the Observable Item table it sometimes includes spurious leading carriage return, leading to a paste with an empty cell followed by the species name. This PR will just remove empty cells from the paste data.

Remove empty cells when pasting

---

api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/SiteValidation.java

Display as a single warning for each ecoregion instead of a different warning for each site.

Improve MEOW validation formatting

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/CorrectionController.java
api/src/main/java/au/org/aodn/nrmn/restapi/controller/mapping/SurveyDtoMapperConfig.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/generator/SurveyIdentifierGenerator.java
api/src/main/java/au/org/aodn/nrmn/restapi/data/model/Survey.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionService.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/DataValidation.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/SurveyValidation.java
api/src/main/java/au/org/aodn/nrmn/restapi/service/validation/ValidationProcess.java
api/src/test/java/au/org/aodn/nrmn/restapi/service/SurveyIngestionServiceTest.java
api/src/test/resources/testdata/FILL_DATA.sql
db/schema-update/02-add-unattached-location-site.sql
web/src/components/import/JobUpload.js

- add dummy site and location
- handle cases where site has no lat / long and skip validation
- when program is NONE use a difference sequence for generating surveyID and skip some use a difference sequence for generating surveyID

Allow NONE validation for unattached survey ingest

---

api/src/main/java/au/org/aodn/nrmn/restapi/controller/AdminController.java
web/src/components/admin/UserComponent.js

Adds a blunt safety feature to user management preventing a logged in admin from deactivating their own account by mistake.

Prevent admin user from editing own details

---

web/src/components/data-entities/survey/SurveyList.js

Issue [#5199](https://github.com/aodn/backlog/issues/5199)

Hide the unresponsive filter icon (triangle) in the table header.
